System.config({
  "baseURL": "/",
  "defaultJSExtensions": true,
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime",
      "optimisation.modules.system",
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  "paths": {
    "*": "src/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  "meta": {
    "showdown/dist/showdown": {
      "format": "global"
    }
  },
  "map": {
    "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.1.0",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.6",
    "aurelia-http-client": "npm:aurelia-http-client@1.0.0-beta.1",
    "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
    "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
    "aurelia-materialize-bridge": "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
    "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
    "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
    "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
    "babel": "npm:babel-core@5.8.35",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "clean-css": "npm:clean-css@3.4.9",
    "core-js": "npm:core-js@2.1.1",
    "css": "github:systemjs/plugin-css@0.1.20",
    "font-awesome": "npm:font-awesome@4.5.0",
    "google/code-prettify": "github:google/code-prettify@master",
    "jquery": "github:components/jquery@2.1.4",
    "json": "github:systemjs/plugin-json@0.1.0",
    "materialize": "github:Dogfalo/materialize@0.97.5",
    "prettify": "npm:prettify@0.1.7",
    "prism": "github:PrismJS/prism@1.3.0",
    "showdown": "github:showdownjs/showdown@1.3.0",
    "showdown-prettify": "npm:showdown-prettify@1.3.0",
    "split.js": "npm:split.js@1.0.6",
    "text": "github:systemjs/plugin-text@0.0.4",
    "github:Dogfalo/materialize@0.97.5": {
      "css": "github:systemjs/plugin-css@0.1.20",
      "jquery": "github:components/jquery@2.1.4"
    },
    "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "materialize": "github:Dogfalo/materialize@0.97.5"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-tty@0.1.0": {
      "tty-browserify": "npm:tty-browserify@0.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:abbrev@1.0.7": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:amdefine@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-binding@1.0.0-beta.1.1.3": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.1.0",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.6",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.1.1",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.1.1",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.1.1",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.1.3",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.1.2",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.1.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.1.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.1.0",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.1.0",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1.1.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-framework@1.0.0-beta.1.0.6": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.1.1": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-http-client@1.0.0-beta.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.1.1": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-loader@1.0.0-beta.1.1.1": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1.1.3": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.1.4": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.1.2": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1.1.0": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-router@1.0.0-beta.1.1.0": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.1.0",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1.1.0",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.1.1": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.1.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.1.0": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.1.0": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.1.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.1.1"
    },
    "npm:aurelia-templating@1.0.0-beta.1.1.1": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "core-js": "npm:core-js@2.1.1"
    },
    "npm:babel-runtime@5.8.35": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:clean-css@3.4.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "commander": "npm:commander@2.8.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.4.4",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:cliui@3.1.0": {
      "string-width": "npm:string-width@1.0.1",
      "strip-ansi": "npm:strip-ansi@3.0.0",
      "wrap-ansi": "npm:wrap-ansi@1.0.0"
    },
    "npm:code-point-at@1.0.0": {
      "number-is-nan": "npm:number-is-nan@1.0.0"
    },
    "npm:commander@2.8.1": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graceful-readlink": "npm:graceful-readlink@1.0.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:config-chain@1.1.10": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "ini": "npm:ini@1.3.4",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "proto-list": "npm:proto-list@1.2.4",
      "url": "github:jspm/nodelibs-url@0.1.0"
    },
    "npm:core-js@2.1.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:decamelize@1.1.2": {
      "escape-string-regexp": "npm:escape-string-regexp@1.0.4"
    },
    "npm:font-awesome@4.5.0": {
      "css": "github:systemjs/plugin-css@0.1.20"
    },
    "npm:graceful-readlink@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:ini@1.3.4": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:is-fullwidth-code-point@1.0.0": {
      "number-is-nan": "npm:number-is-nan@1.0.0"
    },
    "npm:js-prettify@1.4.0": {
      "config-chain": "npm:config-chain@1.1.10",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "mkdirp": "npm:mkdirp@0.3.5",
      "nopt": "npm:nopt@2.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:lcid@1.0.0": {
      "invert-kv": "npm:invert-kv@1.0.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:lodash@1.3.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:mkdirp@0.3.5": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:nopt@2.1.2": {
      "abbrev": "npm:abbrev@1.0.7",
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:os-locale@1.4.0": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "lcid": "npm:lcid@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:prettify@0.1.7": {
      "js-prettify": "npm:js-prettify@1.4.0",
      "lodash": "npm:lodash@1.3.1"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:showdown-prettify@1.3.0": {
      "showdown": "npm:showdown@1.3.0"
    },
    "npm:showdown@1.3.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "yargs": "npm:yargs@3.32.0"
    },
    "npm:source-map@0.4.4": {
      "amdefine": "npm:amdefine@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string-width@1.0.1": {
      "code-point-at": "npm:code-point-at@1.0.0",
      "is-fullwidth-code-point": "npm:is-fullwidth-code-point@1.0.0",
      "strip-ansi": "npm:strip-ansi@3.0.0"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:strip-ansi@3.0.0": {
      "ansi-regex": "npm:ansi-regex@2.0.0"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:window-size@0.1.4": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tty": "github:jspm/nodelibs-tty@0.1.0"
    },
    "npm:wrap-ansi@1.0.0": {
      "string-width": "npm:string-width@1.0.1"
    },
    "npm:y18n@3.2.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:yargs@3.32.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "camelcase": "npm:camelcase@2.1.0",
      "cliui": "npm:cliui@3.1.0",
      "decamelize": "npm:decamelize@1.1.2",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "os-locale": "npm:os-locale@1.4.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "string-width": "npm:string-width@1.0.1",
      "window-size": "npm:window-size@0.1.4",
      "y18n": "npm:y18n@3.2.0"
    }
  },
  "bundles": {
    "materialize-b6ca09cb00": [
      "github:Dogfalo/materialize@0.97.5",
      "github:Dogfalo/materialize@0.97.5/css/materialize.css!github:systemjs/plugin-css@0.1.20",
      "github:Dogfalo/materialize@0.97.5/js/materialize",
      "github:components/jquery@2.1.4",
      "github:components/jquery@2.1.4/jquery"
    ],
    "app-build-b35f70a94a": [
      "about/about",
      "about/about.html!github:systemjs/plugin-text@0.0.4",
      "app",
      "app.html!github:systemjs/plugin-text@0.0.4",
      "github:PrismJS/prism@1.3.0",
      "github:PrismJS/prism@1.3.0/prism",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/badge/badge",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/box/box",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/button/button",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/card/card",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/card/card.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/carousel/carousel",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/carousel/carousel-item",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/carousel/carousel-item.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/carousel/carousel.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/char-counter/char-counter",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/checkbox/checkbox",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/checkbox/checkbox.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/click-counter",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/click-counter.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collapsible/collapsible",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/colors/colorValueConverters",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/colors/md-colors.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/common/attributeManager",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/common/attributes",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/common/constants",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/common/events",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/config-builder",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/datepicker/datepicker",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/dropdown/dropdown",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/dropdown/dropdown-element",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/dropdown/dropdown-element.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/fab/fab",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/fab/fab.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/file/file",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/file/file.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/index",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/input/input",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/input/input-update-service",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/input/input.css!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/input/input.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/modal/modal-trigger",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/navbar/navbar",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/navbar/navbar.css!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/navbar/navbar.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/parallax/parallax",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/pushpin/pushpin",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/radio/radio",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/radio/radio.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/range/range",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/range/range.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/scrollfire/scrollfire",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/scrollfire/scrollfire-patch",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/scrollfire/scrollfire-target",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/scrollspy/scrollspy",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/select/select",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/sidenav/sidenav",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/sidenav/sidenav-collapse",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/sidenav/sidenav.css!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/sidenav/sidenav.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/slider/slider",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/slider/slider.css!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/switch/switch",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/switch/switch.css!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/switch/switch.html!github:systemjs/plugin-text@0.0.4",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/tabs/tabs",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/toast/toastService",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/tooltip/tooltip",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/transitions/fadein-image",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/transitions/staggered-list",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/waves/waves",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/well/md-well.html!github:systemjs/plugin-text@0.0.4",
      "github:components/jquery@2.1.4",
      "github:components/jquery@2.1.4/jquery",
      "github:jspm/nodelibs-process@0.1.2",
      "github:jspm/nodelibs-process@0.1.2/index",
      "github:showdownjs/showdown@1.3.0",
      "github:showdownjs/showdown@1.3.0/dist/showdown",
      "github:systemjs/plugin-css@0.1.20",
      "github:systemjs/plugin-css@0.1.20/css",
      "github:systemjs/plugin-json@0.1.0",
      "github:systemjs/plugin-json@0.1.0/json",
      "github:systemjs/plugin-text@0.0.4",
      "github:systemjs/plugin-text@0.0.4/text",
      "installation/installation",
      "installation/installation.html!github:systemjs/plugin-text@0.0.4",
      "main",
      "nav-bar",
      "nav-bar.html!github:systemjs/plugin-text@0.0.4",
      "npm:aurelia-binding@1.0.0-beta.1.1.3",
      "npm:aurelia-binding@1.0.0-beta.1.1.3/aurelia-binding",
      "npm:aurelia-bootstrapper@1.0.0-beta.1",
      "npm:aurelia-bootstrapper@1.0.0-beta.1/aurelia-bootstrapper",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.1.3/aurelia-dependency-injection",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.1.0",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.1.0/aurelia-event-aggregator",
      "npm:aurelia-framework@1.0.0-beta.1.0.6",
      "npm:aurelia-framework@1.0.0-beta.1.0.6/aurelia-framework",
      "npm:aurelia-history-browser@1.0.0-beta.1.1.1",
      "npm:aurelia-history-browser@1.0.0-beta.1.1.1/aurelia-history-browser",
      "npm:aurelia-history@1.0.0-beta.1.1.1",
      "npm:aurelia-history@1.0.0-beta.1.1.1/aurelia-history",
      "npm:aurelia-loader-default@1.0.0-beta.1.1.1",
      "npm:aurelia-loader-default@1.0.0-beta.1.1.1/aurelia-loader-default",
      "npm:aurelia-loader@1.0.0-beta.1.1.1",
      "npm:aurelia-loader@1.0.0-beta.1.1.1/aurelia-loader",
      "npm:aurelia-logging-console@1.0.0-beta.1.1.3",
      "npm:aurelia-logging-console@1.0.0-beta.1.1.3/aurelia-logging-console",
      "npm:aurelia-logging@1.0.0-beta.1.1.1",
      "npm:aurelia-logging@1.0.0-beta.1.1.1/aurelia-logging",
      "npm:aurelia-metadata@1.0.0-beta.1.1.4",
      "npm:aurelia-metadata@1.0.0-beta.1.1.4/aurelia-metadata",
      "npm:aurelia-pal-browser@1.0.0-beta.1.1.2",
      "npm:aurelia-pal-browser@1.0.0-beta.1.1.2/aurelia-pal-browser",
      "npm:aurelia-pal@1.0.0-beta.1.1.1",
      "npm:aurelia-pal@1.0.0-beta.1.1.1/aurelia-pal",
      "npm:aurelia-path@1.0.0-beta.1.1.0",
      "npm:aurelia-path@1.0.0-beta.1.1.0/aurelia-path",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.1.0",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.1.0/aurelia-route-recognizer",
      "npm:aurelia-router@1.0.0-beta.1.1.0",
      "npm:aurelia-router@1.0.0-beta.1.1.0/aurelia-router",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1",
      "npm:aurelia-task-queue@1.0.0-beta.1.1.1/aurelia-task-queue",
      "npm:aurelia-templating-binding@1.0.0-beta.1.1.0",
      "npm:aurelia-templating-binding@1.0.0-beta.1.1.0/aurelia-templating-binding",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/analyze-view-factory",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/array-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/aurelia-templating-resources",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/binding-mode-behaviors",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/binding-signaler",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/compile-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/compose",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/css-resource",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/debounce-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/dynamic-element",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/focus",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/html-sanitizer",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/if",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/map-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/null-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/number-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/repeat",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/repeat-strategy-locator",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/repeat-utilities",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/replaceable",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/sanitize-html",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/set-repeat-strategy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/show",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/signal-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/throttle-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/update-trigger-binding-behavior",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/view-spy",
      "npm:aurelia-templating-resources@1.0.0-beta.1.1.0/with",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0/aurelia-templating-router",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0/route-href",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0/route-loader",
      "npm:aurelia-templating-router@1.0.0-beta.1.1.0/router-view",
      "npm:aurelia-templating@1.0.0-beta.1.1.1",
      "npm:aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating",
      "npm:babel-core@5.8.35",
      "npm:babel-core@5.8.35/browser",
      "npm:core-js@2.1.1",
      "npm:core-js@2.1.1/index",
      "npm:core-js@2.1.1/library/core",
      "npm:core-js@2.1.1/library/core/_",
      "npm:core-js@2.1.1/library/core/delay",
      "npm:core-js@2.1.1/library/core/dict",
      "npm:core-js@2.1.1/library/core/function",
      "npm:core-js@2.1.1/library/core/index",
      "npm:core-js@2.1.1/library/core/number",
      "npm:core-js@2.1.1/library/core/object",
      "npm:core-js@2.1.1/library/core/regexp",
      "npm:core-js@2.1.1/library/core/string",
      "npm:core-js@2.1.1/library/es5",
      "npm:core-js@2.1.1/library/es5/index",
      "npm:core-js@2.1.1/library/es6",
      "npm:core-js@2.1.1/library/es6/array",
      "npm:core-js@2.1.1/library/es6/date",
      "npm:core-js@2.1.1/library/es6/function",
      "npm:core-js@2.1.1/library/es6/index",
      "npm:core-js@2.1.1/library/es6/map",
      "npm:core-js@2.1.1/library/es6/math",
      "npm:core-js@2.1.1/library/es6/number",
      "npm:core-js@2.1.1/library/es6/object",
      "npm:core-js@2.1.1/library/es6/parse-float",
      "npm:core-js@2.1.1/library/es6/parse-int",
      "npm:core-js@2.1.1/library/es6/promise",
      "npm:core-js@2.1.1/library/es6/reflect",
      "npm:core-js@2.1.1/library/es6/regexp",
      "npm:core-js@2.1.1/library/es6/set",
      "npm:core-js@2.1.1/library/es6/string",
      "npm:core-js@2.1.1/library/es6/symbol",
      "npm:core-js@2.1.1/library/es6/typed",
      "npm:core-js@2.1.1/library/es6/weak-map",
      "npm:core-js@2.1.1/library/es6/weak-set",
      "npm:core-js@2.1.1/library/es7",
      "npm:core-js@2.1.1/library/es7/array",
      "npm:core-js@2.1.1/library/es7/error",
      "npm:core-js@2.1.1/library/es7/index",
      "npm:core-js@2.1.1/library/es7/map",
      "npm:core-js@2.1.1/library/es7/math",
      "npm:core-js@2.1.1/library/es7/object",
      "npm:core-js@2.1.1/library/es7/reflect",
      "npm:core-js@2.1.1/library/es7/set",
      "npm:core-js@2.1.1/library/es7/string",
      "npm:core-js@2.1.1/library/es7/system",
      "npm:core-js@2.1.1/library/fn/_",
      "npm:core-js@2.1.1/library/fn/array",
      "npm:core-js@2.1.1/library/fn/array/concat",
      "npm:core-js@2.1.1/library/fn/array/copy-within",
      "npm:core-js@2.1.1/library/fn/array/entries",
      "npm:core-js@2.1.1/library/fn/array/every",
      "npm:core-js@2.1.1/library/fn/array/fill",
      "npm:core-js@2.1.1/library/fn/array/filter",
      "npm:core-js@2.1.1/library/fn/array/find",
      "npm:core-js@2.1.1/library/fn/array/find-index",
      "npm:core-js@2.1.1/library/fn/array/for-each",
      "npm:core-js@2.1.1/library/fn/array/from",
      "npm:core-js@2.1.1/library/fn/array/includes",
      "npm:core-js@2.1.1/library/fn/array/index",
      "npm:core-js@2.1.1/library/fn/array/index-of",
      "npm:core-js@2.1.1/library/fn/array/is-array",
      "npm:core-js@2.1.1/library/fn/array/iterator",
      "npm:core-js@2.1.1/library/fn/array/join",
      "npm:core-js@2.1.1/library/fn/array/keys",
      "npm:core-js@2.1.1/library/fn/array/last-index-of",
      "npm:core-js@2.1.1/library/fn/array/map",
      "npm:core-js@2.1.1/library/fn/array/of",
      "npm:core-js@2.1.1/library/fn/array/pop",
      "npm:core-js@2.1.1/library/fn/array/push",
      "npm:core-js@2.1.1/library/fn/array/reduce",
      "npm:core-js@2.1.1/library/fn/array/reduce-right",
      "npm:core-js@2.1.1/library/fn/array/reverse",
      "npm:core-js@2.1.1/library/fn/array/shift",
      "npm:core-js@2.1.1/library/fn/array/slice",
      "npm:core-js@2.1.1/library/fn/array/some",
      "npm:core-js@2.1.1/library/fn/array/sort",
      "npm:core-js@2.1.1/library/fn/array/splice",
      "npm:core-js@2.1.1/library/fn/array/unshift",
      "npm:core-js@2.1.1/library/fn/array/values",
      "npm:core-js@2.1.1/library/fn/array/virtual",
      "npm:core-js@2.1.1/library/fn/array/virtual/copy-within",
      "npm:core-js@2.1.1/library/fn/array/virtual/entries",
      "npm:core-js@2.1.1/library/fn/array/virtual/every",
      "npm:core-js@2.1.1/library/fn/array/virtual/fill",
      "npm:core-js@2.1.1/library/fn/array/virtual/filter",
      "npm:core-js@2.1.1/library/fn/array/virtual/find",
      "npm:core-js@2.1.1/library/fn/array/virtual/find-index",
      "npm:core-js@2.1.1/library/fn/array/virtual/for-each",
      "npm:core-js@2.1.1/library/fn/array/virtual/includes",
      "npm:core-js@2.1.1/library/fn/array/virtual/index",
      "npm:core-js@2.1.1/library/fn/array/virtual/index-of",
      "npm:core-js@2.1.1/library/fn/array/virtual/iterator",
      "npm:core-js@2.1.1/library/fn/array/virtual/join",
      "npm:core-js@2.1.1/library/fn/array/virtual/keys",
      "npm:core-js@2.1.1/library/fn/array/virtual/last-index-of",
      "npm:core-js@2.1.1/library/fn/array/virtual/map",
      "npm:core-js@2.1.1/library/fn/array/virtual/reduce",
      "npm:core-js@2.1.1/library/fn/array/virtual/reduce-right",
      "npm:core-js@2.1.1/library/fn/array/virtual/slice",
      "npm:core-js@2.1.1/library/fn/array/virtual/some",
      "npm:core-js@2.1.1/library/fn/array/virtual/sort",
      "npm:core-js@2.1.1/library/fn/array/virtual/values",
      "npm:core-js@2.1.1/library/fn/clear-immediate",
      "npm:core-js@2.1.1/library/fn/date",
      "npm:core-js@2.1.1/library/fn/date/index",
      "npm:core-js@2.1.1/library/fn/date/now",
      "npm:core-js@2.1.1/library/fn/date/to-iso-string",
      "npm:core-js@2.1.1/library/fn/date/to-json",
      "npm:core-js@2.1.1/library/fn/date/to-string",
      "npm:core-js@2.1.1/library/fn/delay",
      "npm:core-js@2.1.1/library/fn/dict",
      "npm:core-js@2.1.1/library/fn/dom-collections",
      "npm:core-js@2.1.1/library/fn/dom-collections/index",
      "npm:core-js@2.1.1/library/fn/dom-collections/iterator",
      "npm:core-js@2.1.1/library/fn/error",
      "npm:core-js@2.1.1/library/fn/error/index",
      "npm:core-js@2.1.1/library/fn/error/is-error",
      "npm:core-js@2.1.1/library/fn/function",
      "npm:core-js@2.1.1/library/fn/function/bind",
      "npm:core-js@2.1.1/library/fn/function/has-instance",
      "npm:core-js@2.1.1/library/fn/function/index",
      "npm:core-js@2.1.1/library/fn/function/name",
      "npm:core-js@2.1.1/library/fn/function/part",
      "npm:core-js@2.1.1/library/fn/function/virtual",
      "npm:core-js@2.1.1/library/fn/function/virtual/bind",
      "npm:core-js@2.1.1/library/fn/function/virtual/index",
      "npm:core-js@2.1.1/library/fn/function/virtual/part",
      "npm:core-js@2.1.1/library/fn/get-iterator",
      "npm:core-js@2.1.1/library/fn/get-iterator-method",
      "npm:core-js@2.1.1/library/fn/is-iterable",
      "npm:core-js@2.1.1/library/fn/json",
      "npm:core-js@2.1.1/library/fn/json/index",
      "npm:core-js@2.1.1/library/fn/json/stringify",
      "npm:core-js@2.1.1/library/fn/map",
      "npm:core-js@2.1.1/library/fn/math",
      "npm:core-js@2.1.1/library/fn/math/acosh",
      "npm:core-js@2.1.1/library/fn/math/asinh",
      "npm:core-js@2.1.1/library/fn/math/atanh",
      "npm:core-js@2.1.1/library/fn/math/cbrt",
      "npm:core-js@2.1.1/library/fn/math/clz32",
      "npm:core-js@2.1.1/library/fn/math/cosh",
      "npm:core-js@2.1.1/library/fn/math/expm1",
      "npm:core-js@2.1.1/library/fn/math/fround",
      "npm:core-js@2.1.1/library/fn/math/hypot",
      "npm:core-js@2.1.1/library/fn/math/iaddh",
      "npm:core-js@2.1.1/library/fn/math/imul",
      "npm:core-js@2.1.1/library/fn/math/imulh",
      "npm:core-js@2.1.1/library/fn/math/index",
      "npm:core-js@2.1.1/library/fn/math/isubh",
      "npm:core-js@2.1.1/library/fn/math/log10",
      "npm:core-js@2.1.1/library/fn/math/log1p",
      "npm:core-js@2.1.1/library/fn/math/log2",
      "npm:core-js@2.1.1/library/fn/math/sign",
      "npm:core-js@2.1.1/library/fn/math/sinh",
      "npm:core-js@2.1.1/library/fn/math/tanh",
      "npm:core-js@2.1.1/library/fn/math/trunc",
      "npm:core-js@2.1.1/library/fn/math/umulh",
      "npm:core-js@2.1.1/library/fn/number",
      "npm:core-js@2.1.1/library/fn/number/constructor",
      "npm:core-js@2.1.1/library/fn/number/epsilon",
      "npm:core-js@2.1.1/library/fn/number/index",
      "npm:core-js@2.1.1/library/fn/number/is-finite",
      "npm:core-js@2.1.1/library/fn/number/is-integer",
      "npm:core-js@2.1.1/library/fn/number/is-nan",
      "npm:core-js@2.1.1/library/fn/number/is-safe-integer",
      "npm:core-js@2.1.1/library/fn/number/iterator",
      "npm:core-js@2.1.1/library/fn/number/max-safe-integer",
      "npm:core-js@2.1.1/library/fn/number/min-safe-integer",
      "npm:core-js@2.1.1/library/fn/number/parse-float",
      "npm:core-js@2.1.1/library/fn/number/parse-int",
      "npm:core-js@2.1.1/library/fn/number/to-fixed",
      "npm:core-js@2.1.1/library/fn/number/to-precision",
      "npm:core-js@2.1.1/library/fn/number/virtual",
      "npm:core-js@2.1.1/library/fn/number/virtual/index",
      "npm:core-js@2.1.1/library/fn/number/virtual/iterator",
      "npm:core-js@2.1.1/library/fn/number/virtual/to-fixed",
      "npm:core-js@2.1.1/library/fn/number/virtual/to-precision",
      "npm:core-js@2.1.1/library/fn/object",
      "npm:core-js@2.1.1/library/fn/object/assign",
      "npm:core-js@2.1.1/library/fn/object/classof",
      "npm:core-js@2.1.1/library/fn/object/create",
      "npm:core-js@2.1.1/library/fn/object/define",
      "npm:core-js@2.1.1/library/fn/object/define-properties",
      "npm:core-js@2.1.1/library/fn/object/define-property",
      "npm:core-js@2.1.1/library/fn/object/entries",
      "npm:core-js@2.1.1/library/fn/object/freeze",
      "npm:core-js@2.1.1/library/fn/object/get-own-property-descriptor",
      "npm:core-js@2.1.1/library/fn/object/get-own-property-descriptors",
      "npm:core-js@2.1.1/library/fn/object/get-own-property-names",
      "npm:core-js@2.1.1/library/fn/object/get-own-property-symbols",
      "npm:core-js@2.1.1/library/fn/object/get-prototype-of",
      "npm:core-js@2.1.1/library/fn/object/index",
      "npm:core-js@2.1.1/library/fn/object/is",
      "npm:core-js@2.1.1/library/fn/object/is-extensible",
      "npm:core-js@2.1.1/library/fn/object/is-frozen",
      "npm:core-js@2.1.1/library/fn/object/is-object",
      "npm:core-js@2.1.1/library/fn/object/is-sealed",
      "npm:core-js@2.1.1/library/fn/object/keys",
      "npm:core-js@2.1.1/library/fn/object/make",
      "npm:core-js@2.1.1/library/fn/object/prevent-extensions",
      "npm:core-js@2.1.1/library/fn/object/seal",
      "npm:core-js@2.1.1/library/fn/object/set-prototype-of",
      "npm:core-js@2.1.1/library/fn/object/values",
      "npm:core-js@2.1.1/library/fn/parse-float",
      "npm:core-js@2.1.1/library/fn/parse-int",
      "npm:core-js@2.1.1/library/fn/promise",
      "npm:core-js@2.1.1/library/fn/reflect",
      "npm:core-js@2.1.1/library/fn/reflect/apply",
      "npm:core-js@2.1.1/library/fn/reflect/construct",
      "npm:core-js@2.1.1/library/fn/reflect/define-metadata",
      "npm:core-js@2.1.1/library/fn/reflect/define-property",
      "npm:core-js@2.1.1/library/fn/reflect/delete-metadata",
      "npm:core-js@2.1.1/library/fn/reflect/delete-property",
      "npm:core-js@2.1.1/library/fn/reflect/enumerate",
      "npm:core-js@2.1.1/library/fn/reflect/get",
      "npm:core-js@2.1.1/library/fn/reflect/get-metadata",
      "npm:core-js@2.1.1/library/fn/reflect/get-metadata-keys",
      "npm:core-js@2.1.1/library/fn/reflect/get-own-metadata",
      "npm:core-js@2.1.1/library/fn/reflect/get-own-metadata-keys",
      "npm:core-js@2.1.1/library/fn/reflect/get-own-property-descriptor",
      "npm:core-js@2.1.1/library/fn/reflect/get-prototype-of",
      "npm:core-js@2.1.1/library/fn/reflect/has",
      "npm:core-js@2.1.1/library/fn/reflect/has-metadata",
      "npm:core-js@2.1.1/library/fn/reflect/has-own-metadata",
      "npm:core-js@2.1.1/library/fn/reflect/index",
      "npm:core-js@2.1.1/library/fn/reflect/is-extensible",
      "npm:core-js@2.1.1/library/fn/reflect/metadata",
      "npm:core-js@2.1.1/library/fn/reflect/own-keys",
      "npm:core-js@2.1.1/library/fn/reflect/prevent-extensions",
      "npm:core-js@2.1.1/library/fn/reflect/set",
      "npm:core-js@2.1.1/library/fn/reflect/set-prototype-of",
      "npm:core-js@2.1.1/library/fn/regexp",
      "npm:core-js@2.1.1/library/fn/regexp/constructor",
      "npm:core-js@2.1.1/library/fn/regexp/escape",
      "npm:core-js@2.1.1/library/fn/regexp/flags",
      "npm:core-js@2.1.1/library/fn/regexp/index",
      "npm:core-js@2.1.1/library/fn/regexp/match",
      "npm:core-js@2.1.1/library/fn/regexp/replace",
      "npm:core-js@2.1.1/library/fn/regexp/search",
      "npm:core-js@2.1.1/library/fn/regexp/split",
      "npm:core-js@2.1.1/library/fn/regexp/to-string",
      "npm:core-js@2.1.1/library/fn/set",
      "npm:core-js@2.1.1/library/fn/set-immediate",
      "npm:core-js@2.1.1/library/fn/set-interval",
      "npm:core-js@2.1.1/library/fn/set-timeout",
      "npm:core-js@2.1.1/library/fn/string",
      "npm:core-js@2.1.1/library/fn/string/anchor",
      "npm:core-js@2.1.1/library/fn/string/at",
      "npm:core-js@2.1.1/library/fn/string/big",
      "npm:core-js@2.1.1/library/fn/string/blink",
      "npm:core-js@2.1.1/library/fn/string/bold",
      "npm:core-js@2.1.1/library/fn/string/code-point-at",
      "npm:core-js@2.1.1/library/fn/string/ends-with",
      "npm:core-js@2.1.1/library/fn/string/escape-html",
      "npm:core-js@2.1.1/library/fn/string/fixed",
      "npm:core-js@2.1.1/library/fn/string/fontcolor",
      "npm:core-js@2.1.1/library/fn/string/fontsize",
      "npm:core-js@2.1.1/library/fn/string/from-code-point",
      "npm:core-js@2.1.1/library/fn/string/includes",
      "npm:core-js@2.1.1/library/fn/string/index",
      "npm:core-js@2.1.1/library/fn/string/italics",
      "npm:core-js@2.1.1/library/fn/string/iterator",
      "npm:core-js@2.1.1/library/fn/string/link",
      "npm:core-js@2.1.1/library/fn/string/pad-end",
      "npm:core-js@2.1.1/library/fn/string/pad-start",
      "npm:core-js@2.1.1/library/fn/string/raw",
      "npm:core-js@2.1.1/library/fn/string/repeat",
      "npm:core-js@2.1.1/library/fn/string/small",
      "npm:core-js@2.1.1/library/fn/string/starts-with",
      "npm:core-js@2.1.1/library/fn/string/strike",
      "npm:core-js@2.1.1/library/fn/string/sub",
      "npm:core-js@2.1.1/library/fn/string/sup",
      "npm:core-js@2.1.1/library/fn/string/trim",
      "npm:core-js@2.1.1/library/fn/string/trim-end",
      "npm:core-js@2.1.1/library/fn/string/trim-left",
      "npm:core-js@2.1.1/library/fn/string/trim-right",
      "npm:core-js@2.1.1/library/fn/string/trim-start",
      "npm:core-js@2.1.1/library/fn/string/unescape-html",
      "npm:core-js@2.1.1/library/fn/string/virtual",
      "npm:core-js@2.1.1/library/fn/string/virtual/anchor",
      "npm:core-js@2.1.1/library/fn/string/virtual/at",
      "npm:core-js@2.1.1/library/fn/string/virtual/big",
      "npm:core-js@2.1.1/library/fn/string/virtual/blink",
      "npm:core-js@2.1.1/library/fn/string/virtual/bold",
      "npm:core-js@2.1.1/library/fn/string/virtual/code-point-at",
      "npm:core-js@2.1.1/library/fn/string/virtual/ends-with",
      "npm:core-js@2.1.1/library/fn/string/virtual/escape-html",
      "npm:core-js@2.1.1/library/fn/string/virtual/fixed",
      "npm:core-js@2.1.1/library/fn/string/virtual/fontcolor",
      "npm:core-js@2.1.1/library/fn/string/virtual/fontsize",
      "npm:core-js@2.1.1/library/fn/string/virtual/includes",
      "npm:core-js@2.1.1/library/fn/string/virtual/index",
      "npm:core-js@2.1.1/library/fn/string/virtual/italics",
      "npm:core-js@2.1.1/library/fn/string/virtual/iterator",
      "npm:core-js@2.1.1/library/fn/string/virtual/link",
      "npm:core-js@2.1.1/library/fn/string/virtual/pad-end",
      "npm:core-js@2.1.1/library/fn/string/virtual/pad-start",
      "npm:core-js@2.1.1/library/fn/string/virtual/repeat",
      "npm:core-js@2.1.1/library/fn/string/virtual/small",
      "npm:core-js@2.1.1/library/fn/string/virtual/starts-with",
      "npm:core-js@2.1.1/library/fn/string/virtual/strike",
      "npm:core-js@2.1.1/library/fn/string/virtual/sub",
      "npm:core-js@2.1.1/library/fn/string/virtual/sup",
      "npm:core-js@2.1.1/library/fn/string/virtual/trim",
      "npm:core-js@2.1.1/library/fn/string/virtual/trim-end",
      "npm:core-js@2.1.1/library/fn/string/virtual/trim-left",
      "npm:core-js@2.1.1/library/fn/string/virtual/trim-right",
      "npm:core-js@2.1.1/library/fn/string/virtual/trim-start",
      "npm:core-js@2.1.1/library/fn/string/virtual/unescape-html",
      "npm:core-js@2.1.1/library/fn/symbol",
      "npm:core-js@2.1.1/library/fn/symbol/for",
      "npm:core-js@2.1.1/library/fn/symbol/has-instance",
      "npm:core-js@2.1.1/library/fn/symbol/index",
      "npm:core-js@2.1.1/library/fn/symbol/is-concat-spreadable",
      "npm:core-js@2.1.1/library/fn/symbol/iterator",
      "npm:core-js@2.1.1/library/fn/symbol/key-for",
      "npm:core-js@2.1.1/library/fn/symbol/match",
      "npm:core-js@2.1.1/library/fn/symbol/replace",
      "npm:core-js@2.1.1/library/fn/symbol/search",
      "npm:core-js@2.1.1/library/fn/symbol/species",
      "npm:core-js@2.1.1/library/fn/symbol/split",
      "npm:core-js@2.1.1/library/fn/symbol/to-primitive",
      "npm:core-js@2.1.1/library/fn/symbol/to-string-tag",
      "npm:core-js@2.1.1/library/fn/symbol/unscopables",
      "npm:core-js@2.1.1/library/fn/system",
      "npm:core-js@2.1.1/library/fn/system/global",
      "npm:core-js@2.1.1/library/fn/system/index",
      "npm:core-js@2.1.1/library/fn/typed",
      "npm:core-js@2.1.1/library/fn/typed/array-buffer",
      "npm:core-js@2.1.1/library/fn/typed/data-view",
      "npm:core-js@2.1.1/library/fn/typed/float32-array",
      "npm:core-js@2.1.1/library/fn/typed/float64-array",
      "npm:core-js@2.1.1/library/fn/typed/index",
      "npm:core-js@2.1.1/library/fn/typed/int16-array",
      "npm:core-js@2.1.1/library/fn/typed/int32-array",
      "npm:core-js@2.1.1/library/fn/typed/int8-array",
      "npm:core-js@2.1.1/library/fn/typed/uint16-array",
      "npm:core-js@2.1.1/library/fn/typed/uint32-array",
      "npm:core-js@2.1.1/library/fn/typed/uint8-array",
      "npm:core-js@2.1.1/library/fn/typed/uint8-clamped-array",
      "npm:core-js@2.1.1/library/fn/weak-map",
      "npm:core-js@2.1.1/library/fn/weak-set",
      "npm:core-js@2.1.1/library/index",
      "npm:core-js@2.1.1/library/modules/_a-function",
      "npm:core-js@2.1.1/library/modules/_a-number-value",
      "npm:core-js@2.1.1/library/modules/_add-to-unscopables",
      "npm:core-js@2.1.1/library/modules/_an-instance",
      "npm:core-js@2.1.1/library/modules/_an-object",
      "npm:core-js@2.1.1/library/modules/_array-copy-within",
      "npm:core-js@2.1.1/library/modules/_array-fill",
      "npm:core-js@2.1.1/library/modules/_array-from-iterable",
      "npm:core-js@2.1.1/library/modules/_array-includes",
      "npm:core-js@2.1.1/library/modules/_array-methods",
      "npm:core-js@2.1.1/library/modules/_array-reduce",
      "npm:core-js@2.1.1/library/modules/_array-species-create",
      "npm:core-js@2.1.1/library/modules/_bind",
      "npm:core-js@2.1.1/library/modules/_classof",
      "npm:core-js@2.1.1/library/modules/_cof",
      "npm:core-js@2.1.1/library/modules/_collection",
      "npm:core-js@2.1.1/library/modules/_collection-strong",
      "npm:core-js@2.1.1/library/modules/_collection-to-json",
      "npm:core-js@2.1.1/library/modules/_collection-weak",
      "npm:core-js@2.1.1/library/modules/_core",
      "npm:core-js@2.1.1/library/modules/_ctx",
      "npm:core-js@2.1.1/library/modules/_defined",
      "npm:core-js@2.1.1/library/modules/_descriptors",
      "npm:core-js@2.1.1/library/modules/_dom-create",
      "npm:core-js@2.1.1/library/modules/_entry-virtual",
      "npm:core-js@2.1.1/library/modules/_enum-bug-keys",
      "npm:core-js@2.1.1/library/modules/_enum-keys",
      "npm:core-js@2.1.1/library/modules/_export",
      "npm:core-js@2.1.1/library/modules/_fails",
      "npm:core-js@2.1.1/library/modules/_fails-is-regexp",
      "npm:core-js@2.1.1/library/modules/_fix-re-wks",
      "npm:core-js@2.1.1/library/modules/_flags",
      "npm:core-js@2.1.1/library/modules/_for-of",
      "npm:core-js@2.1.1/library/modules/_global",
      "npm:core-js@2.1.1/library/modules/_has",
      "npm:core-js@2.1.1/library/modules/_hide",
      "npm:core-js@2.1.1/library/modules/_html",
      "npm:core-js@2.1.1/library/modules/_ie8-dom-define",
      "npm:core-js@2.1.1/library/modules/_inherit-if-required",
      "npm:core-js@2.1.1/library/modules/_invoke",
      "npm:core-js@2.1.1/library/modules/_iobject",
      "npm:core-js@2.1.1/library/modules/_is-array",
      "npm:core-js@2.1.1/library/modules/_is-array-iter",
      "npm:core-js@2.1.1/library/modules/_is-integer",
      "npm:core-js@2.1.1/library/modules/_is-object",
      "npm:core-js@2.1.1/library/modules/_is-regexp",
      "npm:core-js@2.1.1/library/modules/_iter-call",
      "npm:core-js@2.1.1/library/modules/_iter-create",
      "npm:core-js@2.1.1/library/modules/_iter-define",
      "npm:core-js@2.1.1/library/modules/_iter-detect",
      "npm:core-js@2.1.1/library/modules/_iter-step",
      "npm:core-js@2.1.1/library/modules/_iterators",
      "npm:core-js@2.1.1/library/modules/_keyof",
      "npm:core-js@2.1.1/library/modules/_library",
      "npm:core-js@2.1.1/library/modules/_math-expm1",
      "npm:core-js@2.1.1/library/modules/_math-log1p",
      "npm:core-js@2.1.1/library/modules/_math-sign",
      "npm:core-js@2.1.1/library/modules/_meta",
      "npm:core-js@2.1.1/library/modules/_metadata",
      "npm:core-js@2.1.1/library/modules/_microtask",
      "npm:core-js@2.1.1/library/modules/_object-assign",
      "npm:core-js@2.1.1/library/modules/_object-create",
      "npm:core-js@2.1.1/library/modules/_object-define",
      "npm:core-js@2.1.1/library/modules/_object-dp",
      "npm:core-js@2.1.1/library/modules/_object-dps",
      "npm:core-js@2.1.1/library/modules/_object-gopd",
      "npm:core-js@2.1.1/library/modules/_object-gopn",
      "npm:core-js@2.1.1/library/modules/_object-gopn-ext",
      "npm:core-js@2.1.1/library/modules/_object-gops",
      "npm:core-js@2.1.1/library/modules/_object-gpo",
      "npm:core-js@2.1.1/library/modules/_object-keys",
      "npm:core-js@2.1.1/library/modules/_object-keys-internal",
      "npm:core-js@2.1.1/library/modules/_object-pie",
      "npm:core-js@2.1.1/library/modules/_object-sap",
      "npm:core-js@2.1.1/library/modules/_object-to-array",
      "npm:core-js@2.1.1/library/modules/_own-keys",
      "npm:core-js@2.1.1/library/modules/_parse-float",
      "npm:core-js@2.1.1/library/modules/_parse-int",
      "npm:core-js@2.1.1/library/modules/_partial",
      "npm:core-js@2.1.1/library/modules/_path",
      "npm:core-js@2.1.1/library/modules/_property-desc",
      "npm:core-js@2.1.1/library/modules/_redefine",
      "npm:core-js@2.1.1/library/modules/_redefine-all",
      "npm:core-js@2.1.1/library/modules/_replacer",
      "npm:core-js@2.1.1/library/modules/_same-value",
      "npm:core-js@2.1.1/library/modules/_set-proto",
      "npm:core-js@2.1.1/library/modules/_set-species",
      "npm:core-js@2.1.1/library/modules/_set-to-string-tag",
      "npm:core-js@2.1.1/library/modules/_shared",
      "npm:core-js@2.1.1/library/modules/_shared-key",
      "npm:core-js@2.1.1/library/modules/_species-constructor",
      "npm:core-js@2.1.1/library/modules/_strict-method",
      "npm:core-js@2.1.1/library/modules/_string-at",
      "npm:core-js@2.1.1/library/modules/_string-context",
      "npm:core-js@2.1.1/library/modules/_string-html",
      "npm:core-js@2.1.1/library/modules/_string-pad",
      "npm:core-js@2.1.1/library/modules/_string-repeat",
      "npm:core-js@2.1.1/library/modules/_string-trim",
      "npm:core-js@2.1.1/library/modules/_string-ws",
      "npm:core-js@2.1.1/library/modules/_task",
      "npm:core-js@2.1.1/library/modules/_to-index",
      "npm:core-js@2.1.1/library/modules/_to-integer",
      "npm:core-js@2.1.1/library/modules/_to-iobject",
      "npm:core-js@2.1.1/library/modules/_to-length",
      "npm:core-js@2.1.1/library/modules/_to-object",
      "npm:core-js@2.1.1/library/modules/_to-primitive",
      "npm:core-js@2.1.1/library/modules/_typed",
      "npm:core-js@2.1.1/library/modules/_typed-array",
      "npm:core-js@2.1.1/library/modules/_typed-buffer",
      "npm:core-js@2.1.1/library/modules/_uid",
      "npm:core-js@2.1.1/library/modules/_wks",
      "npm:core-js@2.1.1/library/modules/core.delay",
      "npm:core-js@2.1.1/library/modules/core.dict",
      "npm:core-js@2.1.1/library/modules/core.function.part",
      "npm:core-js@2.1.1/library/modules/core.get-iterator",
      "npm:core-js@2.1.1/library/modules/core.get-iterator-method",
      "npm:core-js@2.1.1/library/modules/core.is-iterable",
      "npm:core-js@2.1.1/library/modules/core.number.iterator",
      "npm:core-js@2.1.1/library/modules/core.object.classof",
      "npm:core-js@2.1.1/library/modules/core.object.define",
      "npm:core-js@2.1.1/library/modules/core.object.is-object",
      "npm:core-js@2.1.1/library/modules/core.object.make",
      "npm:core-js@2.1.1/library/modules/core.regexp.escape",
      "npm:core-js@2.1.1/library/modules/core.string.escape-html",
      "npm:core-js@2.1.1/library/modules/core.string.unescape-html",
      "npm:core-js@2.1.1/library/modules/es5",
      "npm:core-js@2.1.1/library/modules/es6.array.copy-within",
      "npm:core-js@2.1.1/library/modules/es6.array.every",
      "npm:core-js@2.1.1/library/modules/es6.array.fill",
      "npm:core-js@2.1.1/library/modules/es6.array.filter",
      "npm:core-js@2.1.1/library/modules/es6.array.find",
      "npm:core-js@2.1.1/library/modules/es6.array.find-index",
      "npm:core-js@2.1.1/library/modules/es6.array.for-each",
      "npm:core-js@2.1.1/library/modules/es6.array.from",
      "npm:core-js@2.1.1/library/modules/es6.array.index-of",
      "npm:core-js@2.1.1/library/modules/es6.array.is-array",
      "npm:core-js@2.1.1/library/modules/es6.array.iterator",
      "npm:core-js@2.1.1/library/modules/es6.array.join",
      "npm:core-js@2.1.1/library/modules/es6.array.last-index-of",
      "npm:core-js@2.1.1/library/modules/es6.array.map",
      "npm:core-js@2.1.1/library/modules/es6.array.of",
      "npm:core-js@2.1.1/library/modules/es6.array.reduce",
      "npm:core-js@2.1.1/library/modules/es6.array.reduce-right",
      "npm:core-js@2.1.1/library/modules/es6.array.slice",
      "npm:core-js@2.1.1/library/modules/es6.array.some",
      "npm:core-js@2.1.1/library/modules/es6.array.sort",
      "npm:core-js@2.1.1/library/modules/es6.array.species",
      "npm:core-js@2.1.1/library/modules/es6.date.now",
      "npm:core-js@2.1.1/library/modules/es6.date.to-iso-string",
      "npm:core-js@2.1.1/library/modules/es6.date.to-json",
      "npm:core-js@2.1.1/library/modules/es6.date.to-string",
      "npm:core-js@2.1.1/library/modules/es6.function.bind",
      "npm:core-js@2.1.1/library/modules/es6.function.has-instance",
      "npm:core-js@2.1.1/library/modules/es6.function.name",
      "npm:core-js@2.1.1/library/modules/es6.map",
      "npm:core-js@2.1.1/library/modules/es6.math.acosh",
      "npm:core-js@2.1.1/library/modules/es6.math.asinh",
      "npm:core-js@2.1.1/library/modules/es6.math.atanh",
      "npm:core-js@2.1.1/library/modules/es6.math.cbrt",
      "npm:core-js@2.1.1/library/modules/es6.math.clz32",
      "npm:core-js@2.1.1/library/modules/es6.math.cosh",
      "npm:core-js@2.1.1/library/modules/es6.math.expm1",
      "npm:core-js@2.1.1/library/modules/es6.math.fround",
      "npm:core-js@2.1.1/library/modules/es6.math.hypot",
      "npm:core-js@2.1.1/library/modules/es6.math.imul",
      "npm:core-js@2.1.1/library/modules/es6.math.log10",
      "npm:core-js@2.1.1/library/modules/es6.math.log1p",
      "npm:core-js@2.1.1/library/modules/es6.math.log2",
      "npm:core-js@2.1.1/library/modules/es6.math.sign",
      "npm:core-js@2.1.1/library/modules/es6.math.sinh",
      "npm:core-js@2.1.1/library/modules/es6.math.tanh",
      "npm:core-js@2.1.1/library/modules/es6.math.trunc",
      "npm:core-js@2.1.1/library/modules/es6.number.constructor",
      "npm:core-js@2.1.1/library/modules/es6.number.epsilon",
      "npm:core-js@2.1.1/library/modules/es6.number.is-finite",
      "npm:core-js@2.1.1/library/modules/es6.number.is-integer",
      "npm:core-js@2.1.1/library/modules/es6.number.is-nan",
      "npm:core-js@2.1.1/library/modules/es6.number.is-safe-integer",
      "npm:core-js@2.1.1/library/modules/es6.number.max-safe-integer",
      "npm:core-js@2.1.1/library/modules/es6.number.min-safe-integer",
      "npm:core-js@2.1.1/library/modules/es6.number.parse-float",
      "npm:core-js@2.1.1/library/modules/es6.number.parse-int",
      "npm:core-js@2.1.1/library/modules/es6.number.to-fixed",
      "npm:core-js@2.1.1/library/modules/es6.number.to-precision",
      "npm:core-js@2.1.1/library/modules/es6.object.assign",
      "npm:core-js@2.1.1/library/modules/es6.object.create",
      "npm:core-js@2.1.1/library/modules/es6.object.define-properties",
      "npm:core-js@2.1.1/library/modules/es6.object.define-property",
      "npm:core-js@2.1.1/library/modules/es6.object.freeze",
      "npm:core-js@2.1.1/library/modules/es6.object.get-own-property-descriptor",
      "npm:core-js@2.1.1/library/modules/es6.object.get-own-property-names",
      "npm:core-js@2.1.1/library/modules/es6.object.get-prototype-of",
      "npm:core-js@2.1.1/library/modules/es6.object.is",
      "npm:core-js@2.1.1/library/modules/es6.object.is-extensible",
      "npm:core-js@2.1.1/library/modules/es6.object.is-frozen",
      "npm:core-js@2.1.1/library/modules/es6.object.is-sealed",
      "npm:core-js@2.1.1/library/modules/es6.object.keys",
      "npm:core-js@2.1.1/library/modules/es6.object.prevent-extensions",
      "npm:core-js@2.1.1/library/modules/es6.object.seal",
      "npm:core-js@2.1.1/library/modules/es6.object.set-prototype-of",
      "npm:core-js@2.1.1/library/modules/es6.object.to-string",
      "npm:core-js@2.1.1/library/modules/es6.parse-float",
      "npm:core-js@2.1.1/library/modules/es6.parse-int",
      "npm:core-js@2.1.1/library/modules/es6.promise",
      "npm:core-js@2.1.1/library/modules/es6.reflect.apply",
      "npm:core-js@2.1.1/library/modules/es6.reflect.construct",
      "npm:core-js@2.1.1/library/modules/es6.reflect.define-property",
      "npm:core-js@2.1.1/library/modules/es6.reflect.delete-property",
      "npm:core-js@2.1.1/library/modules/es6.reflect.enumerate",
      "npm:core-js@2.1.1/library/modules/es6.reflect.get",
      "npm:core-js@2.1.1/library/modules/es6.reflect.get-own-property-descriptor",
      "npm:core-js@2.1.1/library/modules/es6.reflect.get-prototype-of",
      "npm:core-js@2.1.1/library/modules/es6.reflect.has",
      "npm:core-js@2.1.1/library/modules/es6.reflect.is-extensible",
      "npm:core-js@2.1.1/library/modules/es6.reflect.own-keys",
      "npm:core-js@2.1.1/library/modules/es6.reflect.prevent-extensions",
      "npm:core-js@2.1.1/library/modules/es6.reflect.set",
      "npm:core-js@2.1.1/library/modules/es6.reflect.set-prototype-of",
      "npm:core-js@2.1.1/library/modules/es6.regexp.constructor",
      "npm:core-js@2.1.1/library/modules/es6.regexp.flags",
      "npm:core-js@2.1.1/library/modules/es6.regexp.match",
      "npm:core-js@2.1.1/library/modules/es6.regexp.replace",
      "npm:core-js@2.1.1/library/modules/es6.regexp.search",
      "npm:core-js@2.1.1/library/modules/es6.regexp.split",
      "npm:core-js@2.1.1/library/modules/es6.regexp.to-string",
      "npm:core-js@2.1.1/library/modules/es6.set",
      "npm:core-js@2.1.1/library/modules/es6.string.anchor",
      "npm:core-js@2.1.1/library/modules/es6.string.big",
      "npm:core-js@2.1.1/library/modules/es6.string.blink",
      "npm:core-js@2.1.1/library/modules/es6.string.bold",
      "npm:core-js@2.1.1/library/modules/es6.string.code-point-at",
      "npm:core-js@2.1.1/library/modules/es6.string.ends-with",
      "npm:core-js@2.1.1/library/modules/es6.string.fixed",
      "npm:core-js@2.1.1/library/modules/es6.string.fontcolor",
      "npm:core-js@2.1.1/library/modules/es6.string.fontsize",
      "npm:core-js@2.1.1/library/modules/es6.string.from-code-point",
      "npm:core-js@2.1.1/library/modules/es6.string.includes",
      "npm:core-js@2.1.1/library/modules/es6.string.italics",
      "npm:core-js@2.1.1/library/modules/es6.string.iterator",
      "npm:core-js@2.1.1/library/modules/es6.string.link",
      "npm:core-js@2.1.1/library/modules/es6.string.raw",
      "npm:core-js@2.1.1/library/modules/es6.string.repeat",
      "npm:core-js@2.1.1/library/modules/es6.string.small",
      "npm:core-js@2.1.1/library/modules/es6.string.starts-with",
      "npm:core-js@2.1.1/library/modules/es6.string.strike",
      "npm:core-js@2.1.1/library/modules/es6.string.sub",
      "npm:core-js@2.1.1/library/modules/es6.string.sup",
      "npm:core-js@2.1.1/library/modules/es6.string.trim",
      "npm:core-js@2.1.1/library/modules/es6.symbol",
      "npm:core-js@2.1.1/library/modules/es6.typed.array-buffer",
      "npm:core-js@2.1.1/library/modules/es6.typed.data-view",
      "npm:core-js@2.1.1/library/modules/es6.typed.float32-array",
      "npm:core-js@2.1.1/library/modules/es6.typed.float64-array",
      "npm:core-js@2.1.1/library/modules/es6.typed.int16-array",
      "npm:core-js@2.1.1/library/modules/es6.typed.int32-array",
      "npm:core-js@2.1.1/library/modules/es6.typed.int8-array",
      "npm:core-js@2.1.1/library/modules/es6.typed.uint16-array",
      "npm:core-js@2.1.1/library/modules/es6.typed.uint32-array",
      "npm:core-js@2.1.1/library/modules/es6.typed.uint8-array",
      "npm:core-js@2.1.1/library/modules/es6.typed.uint8-clamped-array",
      "npm:core-js@2.1.1/library/modules/es6.weak-map",
      "npm:core-js@2.1.1/library/modules/es6.weak-set",
      "npm:core-js@2.1.1/library/modules/es7.array.includes",
      "npm:core-js@2.1.1/library/modules/es7.error.is-error",
      "npm:core-js@2.1.1/library/modules/es7.map.to-json",
      "npm:core-js@2.1.1/library/modules/es7.math.iaddh",
      "npm:core-js@2.1.1/library/modules/es7.math.imulh",
      "npm:core-js@2.1.1/library/modules/es7.math.isubh",
      "npm:core-js@2.1.1/library/modules/es7.math.umulh",
      "npm:core-js@2.1.1/library/modules/es7.object.entries",
      "npm:core-js@2.1.1/library/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@2.1.1/library/modules/es7.object.values",
      "npm:core-js@2.1.1/library/modules/es7.reflect.define-metadata",
      "npm:core-js@2.1.1/library/modules/es7.reflect.delete-metadata",
      "npm:core-js@2.1.1/library/modules/es7.reflect.get-metadata",
      "npm:core-js@2.1.1/library/modules/es7.reflect.get-metadata-keys",
      "npm:core-js@2.1.1/library/modules/es7.reflect.get-own-metadata",
      "npm:core-js@2.1.1/library/modules/es7.reflect.get-own-metadata-keys",
      "npm:core-js@2.1.1/library/modules/es7.reflect.has-metadata",
      "npm:core-js@2.1.1/library/modules/es7.reflect.has-own-metadata",
      "npm:core-js@2.1.1/library/modules/es7.reflect.metadata",
      "npm:core-js@2.1.1/library/modules/es7.set.to-json",
      "npm:core-js@2.1.1/library/modules/es7.string.at",
      "npm:core-js@2.1.1/library/modules/es7.string.match-all",
      "npm:core-js@2.1.1/library/modules/es7.string.pad-end",
      "npm:core-js@2.1.1/library/modules/es7.string.pad-start",
      "npm:core-js@2.1.1/library/modules/es7.string.trim-left",
      "npm:core-js@2.1.1/library/modules/es7.string.trim-right",
      "npm:core-js@2.1.1/library/modules/es7.system.global",
      "npm:core-js@2.1.1/library/modules/web.dom.iterable",
      "npm:core-js@2.1.1/library/modules/web.immediate",
      "npm:core-js@2.1.1/library/modules/web.timers",
      "npm:core-js@2.1.1/library/shim",
      "npm:core-js@2.1.1/library/stage",
      "npm:core-js@2.1.1/library/stage/0",
      "npm:core-js@2.1.1/library/stage/1",
      "npm:core-js@2.1.1/library/stage/2",
      "npm:core-js@2.1.1/library/stage/3",
      "npm:core-js@2.1.1/library/stage/4",
      "npm:core-js@2.1.1/library/stage/index",
      "npm:core-js@2.1.1/library/stage/pre",
      "npm:core-js@2.1.1/library/web",
      "npm:core-js@2.1.1/library/web/dom-collections",
      "npm:core-js@2.1.1/library/web/immediate",
      "npm:core-js@2.1.1/library/web/index",
      "npm:core-js@2.1.1/library/web/timers",
      "npm:core-js@2.1.1/modules/_a-function",
      "npm:core-js@2.1.1/modules/_a-number-value",
      "npm:core-js@2.1.1/modules/_add-to-unscopables",
      "npm:core-js@2.1.1/modules/_an-instance",
      "npm:core-js@2.1.1/modules/_an-object",
      "npm:core-js@2.1.1/modules/_array-copy-within",
      "npm:core-js@2.1.1/modules/_array-fill",
      "npm:core-js@2.1.1/modules/_array-from-iterable",
      "npm:core-js@2.1.1/modules/_array-includes",
      "npm:core-js@2.1.1/modules/_array-methods",
      "npm:core-js@2.1.1/modules/_array-reduce",
      "npm:core-js@2.1.1/modules/_array-species-create",
      "npm:core-js@2.1.1/modules/_bind",
      "npm:core-js@2.1.1/modules/_classof",
      "npm:core-js@2.1.1/modules/_cof",
      "npm:core-js@2.1.1/modules/_collection",
      "npm:core-js@2.1.1/modules/_collection-strong",
      "npm:core-js@2.1.1/modules/_collection-to-json",
      "npm:core-js@2.1.1/modules/_collection-weak",
      "npm:core-js@2.1.1/modules/_core",
      "npm:core-js@2.1.1/modules/_ctx",
      "npm:core-js@2.1.1/modules/_defined",
      "npm:core-js@2.1.1/modules/_descriptors",
      "npm:core-js@2.1.1/modules/_dom-create",
      "npm:core-js@2.1.1/modules/_enum-bug-keys",
      "npm:core-js@2.1.1/modules/_enum-keys",
      "npm:core-js@2.1.1/modules/_export",
      "npm:core-js@2.1.1/modules/_fails",
      "npm:core-js@2.1.1/modules/_fails-is-regexp",
      "npm:core-js@2.1.1/modules/_fix-re-wks",
      "npm:core-js@2.1.1/modules/_flags",
      "npm:core-js@2.1.1/modules/_for-of",
      "npm:core-js@2.1.1/modules/_global",
      "npm:core-js@2.1.1/modules/_has",
      "npm:core-js@2.1.1/modules/_hide",
      "npm:core-js@2.1.1/modules/_html",
      "npm:core-js@2.1.1/modules/_ie8-dom-define",
      "npm:core-js@2.1.1/modules/_inherit-if-required",
      "npm:core-js@2.1.1/modules/_invoke",
      "npm:core-js@2.1.1/modules/_iobject",
      "npm:core-js@2.1.1/modules/_is-array",
      "npm:core-js@2.1.1/modules/_is-array-iter",
      "npm:core-js@2.1.1/modules/_is-integer",
      "npm:core-js@2.1.1/modules/_is-object",
      "npm:core-js@2.1.1/modules/_is-regexp",
      "npm:core-js@2.1.1/modules/_iter-call",
      "npm:core-js@2.1.1/modules/_iter-create",
      "npm:core-js@2.1.1/modules/_iter-define",
      "npm:core-js@2.1.1/modules/_iter-detect",
      "npm:core-js@2.1.1/modules/_iter-step",
      "npm:core-js@2.1.1/modules/_iterators",
      "npm:core-js@2.1.1/modules/_keyof",
      "npm:core-js@2.1.1/modules/_library",
      "npm:core-js@2.1.1/modules/_math-expm1",
      "npm:core-js@2.1.1/modules/_math-log1p",
      "npm:core-js@2.1.1/modules/_math-sign",
      "npm:core-js@2.1.1/modules/_meta",
      "npm:core-js@2.1.1/modules/_metadata",
      "npm:core-js@2.1.1/modules/_microtask",
      "npm:core-js@2.1.1/modules/_object-assign",
      "npm:core-js@2.1.1/modules/_object-create",
      "npm:core-js@2.1.1/modules/_object-define",
      "npm:core-js@2.1.1/modules/_object-dp",
      "npm:core-js@2.1.1/modules/_object-dps",
      "npm:core-js@2.1.1/modules/_object-gopd",
      "npm:core-js@2.1.1/modules/_object-gopn",
      "npm:core-js@2.1.1/modules/_object-gopn-ext",
      "npm:core-js@2.1.1/modules/_object-gops",
      "npm:core-js@2.1.1/modules/_object-gpo",
      "npm:core-js@2.1.1/modules/_object-keys",
      "npm:core-js@2.1.1/modules/_object-keys-internal",
      "npm:core-js@2.1.1/modules/_object-pie",
      "npm:core-js@2.1.1/modules/_object-sap",
      "npm:core-js@2.1.1/modules/_object-to-array",
      "npm:core-js@2.1.1/modules/_own-keys",
      "npm:core-js@2.1.1/modules/_parse-float",
      "npm:core-js@2.1.1/modules/_parse-int",
      "npm:core-js@2.1.1/modules/_partial",
      "npm:core-js@2.1.1/modules/_path",
      "npm:core-js@2.1.1/modules/_property-desc",
      "npm:core-js@2.1.1/modules/_redefine",
      "npm:core-js@2.1.1/modules/_redefine-all",
      "npm:core-js@2.1.1/modules/_replacer",
      "npm:core-js@2.1.1/modules/_same-value",
      "npm:core-js@2.1.1/modules/_set-proto",
      "npm:core-js@2.1.1/modules/_set-species",
      "npm:core-js@2.1.1/modules/_set-to-string-tag",
      "npm:core-js@2.1.1/modules/_shared",
      "npm:core-js@2.1.1/modules/_shared-key",
      "npm:core-js@2.1.1/modules/_species-constructor",
      "npm:core-js@2.1.1/modules/_strict-method",
      "npm:core-js@2.1.1/modules/_string-at",
      "npm:core-js@2.1.1/modules/_string-context",
      "npm:core-js@2.1.1/modules/_string-html",
      "npm:core-js@2.1.1/modules/_string-pad",
      "npm:core-js@2.1.1/modules/_string-repeat",
      "npm:core-js@2.1.1/modules/_string-trim",
      "npm:core-js@2.1.1/modules/_string-ws",
      "npm:core-js@2.1.1/modules/_task",
      "npm:core-js@2.1.1/modules/_to-index",
      "npm:core-js@2.1.1/modules/_to-integer",
      "npm:core-js@2.1.1/modules/_to-iobject",
      "npm:core-js@2.1.1/modules/_to-length",
      "npm:core-js@2.1.1/modules/_to-object",
      "npm:core-js@2.1.1/modules/_to-primitive",
      "npm:core-js@2.1.1/modules/_typed",
      "npm:core-js@2.1.1/modules/_typed-array",
      "npm:core-js@2.1.1/modules/_typed-buffer",
      "npm:core-js@2.1.1/modules/_uid",
      "npm:core-js@2.1.1/modules/_wks",
      "npm:core-js@2.1.1/modules/core.delay",
      "npm:core-js@2.1.1/modules/core.dict",
      "npm:core-js@2.1.1/modules/core.function.part",
      "npm:core-js@2.1.1/modules/core.get-iterator",
      "npm:core-js@2.1.1/modules/core.get-iterator-method",
      "npm:core-js@2.1.1/modules/core.is-iterable",
      "npm:core-js@2.1.1/modules/core.number.iterator",
      "npm:core-js@2.1.1/modules/core.object.classof",
      "npm:core-js@2.1.1/modules/core.object.define",
      "npm:core-js@2.1.1/modules/core.object.is-object",
      "npm:core-js@2.1.1/modules/core.object.make",
      "npm:core-js@2.1.1/modules/core.regexp.escape",
      "npm:core-js@2.1.1/modules/core.string.escape-html",
      "npm:core-js@2.1.1/modules/core.string.unescape-html",
      "npm:core-js@2.1.1/modules/es6.array.copy-within",
      "npm:core-js@2.1.1/modules/es6.array.every",
      "npm:core-js@2.1.1/modules/es6.array.fill",
      "npm:core-js@2.1.1/modules/es6.array.filter",
      "npm:core-js@2.1.1/modules/es6.array.find",
      "npm:core-js@2.1.1/modules/es6.array.find-index",
      "npm:core-js@2.1.1/modules/es6.array.for-each",
      "npm:core-js@2.1.1/modules/es6.array.from",
      "npm:core-js@2.1.1/modules/es6.array.index-of",
      "npm:core-js@2.1.1/modules/es6.array.is-array",
      "npm:core-js@2.1.1/modules/es6.array.iterator",
      "npm:core-js@2.1.1/modules/es6.array.join",
      "npm:core-js@2.1.1/modules/es6.array.last-index-of",
      "npm:core-js@2.1.1/modules/es6.array.map",
      "npm:core-js@2.1.1/modules/es6.array.of",
      "npm:core-js@2.1.1/modules/es6.array.reduce",
      "npm:core-js@2.1.1/modules/es6.array.reduce-right",
      "npm:core-js@2.1.1/modules/es6.array.slice",
      "npm:core-js@2.1.1/modules/es6.array.some",
      "npm:core-js@2.1.1/modules/es6.array.sort",
      "npm:core-js@2.1.1/modules/es6.array.species",
      "npm:core-js@2.1.1/modules/es6.date.now",
      "npm:core-js@2.1.1/modules/es6.date.to-iso-string",
      "npm:core-js@2.1.1/modules/es6.date.to-json",
      "npm:core-js@2.1.1/modules/es6.date.to-string",
      "npm:core-js@2.1.1/modules/es6.function.bind",
      "npm:core-js@2.1.1/modules/es6.function.has-instance",
      "npm:core-js@2.1.1/modules/es6.function.name",
      "npm:core-js@2.1.1/modules/es6.map",
      "npm:core-js@2.1.1/modules/es6.math.acosh",
      "npm:core-js@2.1.1/modules/es6.math.asinh",
      "npm:core-js@2.1.1/modules/es6.math.atanh",
      "npm:core-js@2.1.1/modules/es6.math.cbrt",
      "npm:core-js@2.1.1/modules/es6.math.clz32",
      "npm:core-js@2.1.1/modules/es6.math.cosh",
      "npm:core-js@2.1.1/modules/es6.math.expm1",
      "npm:core-js@2.1.1/modules/es6.math.fround",
      "npm:core-js@2.1.1/modules/es6.math.hypot",
      "npm:core-js@2.1.1/modules/es6.math.imul",
      "npm:core-js@2.1.1/modules/es6.math.log10",
      "npm:core-js@2.1.1/modules/es6.math.log1p",
      "npm:core-js@2.1.1/modules/es6.math.log2",
      "npm:core-js@2.1.1/modules/es6.math.sign",
      "npm:core-js@2.1.1/modules/es6.math.sinh",
      "npm:core-js@2.1.1/modules/es6.math.tanh",
      "npm:core-js@2.1.1/modules/es6.math.trunc",
      "npm:core-js@2.1.1/modules/es6.number.constructor",
      "npm:core-js@2.1.1/modules/es6.number.epsilon",
      "npm:core-js@2.1.1/modules/es6.number.is-finite",
      "npm:core-js@2.1.1/modules/es6.number.is-integer",
      "npm:core-js@2.1.1/modules/es6.number.is-nan",
      "npm:core-js@2.1.1/modules/es6.number.is-safe-integer",
      "npm:core-js@2.1.1/modules/es6.number.max-safe-integer",
      "npm:core-js@2.1.1/modules/es6.number.min-safe-integer",
      "npm:core-js@2.1.1/modules/es6.number.parse-float",
      "npm:core-js@2.1.1/modules/es6.number.parse-int",
      "npm:core-js@2.1.1/modules/es6.number.to-fixed",
      "npm:core-js@2.1.1/modules/es6.number.to-precision",
      "npm:core-js@2.1.1/modules/es6.object.assign",
      "npm:core-js@2.1.1/modules/es6.object.create",
      "npm:core-js@2.1.1/modules/es6.object.define-properties",
      "npm:core-js@2.1.1/modules/es6.object.define-property",
      "npm:core-js@2.1.1/modules/es6.object.freeze",
      "npm:core-js@2.1.1/modules/es6.object.get-own-property-descriptor",
      "npm:core-js@2.1.1/modules/es6.object.get-own-property-names",
      "npm:core-js@2.1.1/modules/es6.object.get-prototype-of",
      "npm:core-js@2.1.1/modules/es6.object.is",
      "npm:core-js@2.1.1/modules/es6.object.is-extensible",
      "npm:core-js@2.1.1/modules/es6.object.is-frozen",
      "npm:core-js@2.1.1/modules/es6.object.is-sealed",
      "npm:core-js@2.1.1/modules/es6.object.keys",
      "npm:core-js@2.1.1/modules/es6.object.prevent-extensions",
      "npm:core-js@2.1.1/modules/es6.object.seal",
      "npm:core-js@2.1.1/modules/es6.object.set-prototype-of",
      "npm:core-js@2.1.1/modules/es6.object.to-string",
      "npm:core-js@2.1.1/modules/es6.parse-float",
      "npm:core-js@2.1.1/modules/es6.parse-int",
      "npm:core-js@2.1.1/modules/es6.promise",
      "npm:core-js@2.1.1/modules/es6.reflect.apply",
      "npm:core-js@2.1.1/modules/es6.reflect.construct",
      "npm:core-js@2.1.1/modules/es6.reflect.define-property",
      "npm:core-js@2.1.1/modules/es6.reflect.delete-property",
      "npm:core-js@2.1.1/modules/es6.reflect.enumerate",
      "npm:core-js@2.1.1/modules/es6.reflect.get",
      "npm:core-js@2.1.1/modules/es6.reflect.get-own-property-descriptor",
      "npm:core-js@2.1.1/modules/es6.reflect.get-prototype-of",
      "npm:core-js@2.1.1/modules/es6.reflect.has",
      "npm:core-js@2.1.1/modules/es6.reflect.is-extensible",
      "npm:core-js@2.1.1/modules/es6.reflect.own-keys",
      "npm:core-js@2.1.1/modules/es6.reflect.prevent-extensions",
      "npm:core-js@2.1.1/modules/es6.reflect.set",
      "npm:core-js@2.1.1/modules/es6.reflect.set-prototype-of",
      "npm:core-js@2.1.1/modules/es6.regexp.constructor",
      "npm:core-js@2.1.1/modules/es6.regexp.flags",
      "npm:core-js@2.1.1/modules/es6.regexp.match",
      "npm:core-js@2.1.1/modules/es6.regexp.replace",
      "npm:core-js@2.1.1/modules/es6.regexp.search",
      "npm:core-js@2.1.1/modules/es6.regexp.split",
      "npm:core-js@2.1.1/modules/es6.regexp.to-string",
      "npm:core-js@2.1.1/modules/es6.set",
      "npm:core-js@2.1.1/modules/es6.string.anchor",
      "npm:core-js@2.1.1/modules/es6.string.big",
      "npm:core-js@2.1.1/modules/es6.string.blink",
      "npm:core-js@2.1.1/modules/es6.string.bold",
      "npm:core-js@2.1.1/modules/es6.string.code-point-at",
      "npm:core-js@2.1.1/modules/es6.string.ends-with",
      "npm:core-js@2.1.1/modules/es6.string.fixed",
      "npm:core-js@2.1.1/modules/es6.string.fontcolor",
      "npm:core-js@2.1.1/modules/es6.string.fontsize",
      "npm:core-js@2.1.1/modules/es6.string.from-code-point",
      "npm:core-js@2.1.1/modules/es6.string.includes",
      "npm:core-js@2.1.1/modules/es6.string.italics",
      "npm:core-js@2.1.1/modules/es6.string.iterator",
      "npm:core-js@2.1.1/modules/es6.string.link",
      "npm:core-js@2.1.1/modules/es6.string.raw",
      "npm:core-js@2.1.1/modules/es6.string.repeat",
      "npm:core-js@2.1.1/modules/es6.string.small",
      "npm:core-js@2.1.1/modules/es6.string.starts-with",
      "npm:core-js@2.1.1/modules/es6.string.strike",
      "npm:core-js@2.1.1/modules/es6.string.sub",
      "npm:core-js@2.1.1/modules/es6.string.sup",
      "npm:core-js@2.1.1/modules/es6.string.trim",
      "npm:core-js@2.1.1/modules/es6.symbol",
      "npm:core-js@2.1.1/modules/es6.typed.array-buffer",
      "npm:core-js@2.1.1/modules/es6.typed.data-view",
      "npm:core-js@2.1.1/modules/es6.typed.float32-array",
      "npm:core-js@2.1.1/modules/es6.typed.float64-array",
      "npm:core-js@2.1.1/modules/es6.typed.int16-array",
      "npm:core-js@2.1.1/modules/es6.typed.int32-array",
      "npm:core-js@2.1.1/modules/es6.typed.int8-array",
      "npm:core-js@2.1.1/modules/es6.typed.uint16-array",
      "npm:core-js@2.1.1/modules/es6.typed.uint32-array",
      "npm:core-js@2.1.1/modules/es6.typed.uint8-array",
      "npm:core-js@2.1.1/modules/es6.typed.uint8-clamped-array",
      "npm:core-js@2.1.1/modules/es6.weak-map",
      "npm:core-js@2.1.1/modules/es6.weak-set",
      "npm:core-js@2.1.1/modules/es7.array.includes",
      "npm:core-js@2.1.1/modules/es7.error.is-error",
      "npm:core-js@2.1.1/modules/es7.map.to-json",
      "npm:core-js@2.1.1/modules/es7.math.iaddh",
      "npm:core-js@2.1.1/modules/es7.math.imulh",
      "npm:core-js@2.1.1/modules/es7.math.isubh",
      "npm:core-js@2.1.1/modules/es7.math.umulh",
      "npm:core-js@2.1.1/modules/es7.object.entries",
      "npm:core-js@2.1.1/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@2.1.1/modules/es7.object.values",
      "npm:core-js@2.1.1/modules/es7.reflect.define-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.delete-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.get-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.get-metadata-keys",
      "npm:core-js@2.1.1/modules/es7.reflect.get-own-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.get-own-metadata-keys",
      "npm:core-js@2.1.1/modules/es7.reflect.has-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.has-own-metadata",
      "npm:core-js@2.1.1/modules/es7.reflect.metadata",
      "npm:core-js@2.1.1/modules/es7.set.to-json",
      "npm:core-js@2.1.1/modules/es7.string.at",
      "npm:core-js@2.1.1/modules/es7.string.pad-end",
      "npm:core-js@2.1.1/modules/es7.string.pad-start",
      "npm:core-js@2.1.1/modules/es7.string.trim-left",
      "npm:core-js@2.1.1/modules/es7.string.trim-right",
      "npm:core-js@2.1.1/modules/es7.system.global",
      "npm:core-js@2.1.1/modules/web.dom.iterable",
      "npm:core-js@2.1.1/modules/web.immediate",
      "npm:core-js@2.1.1/modules/web.timers",
      "npm:core-js@2.1.1/shim",
      "npm:process@0.11.2",
      "npm:process@0.11.2/browser",
      "npm:showdown-prettify@1.3.0",
      "npm:showdown-prettify@1.3.0/dist/showdown-prettify",
      "npm:showdown@1.3.0",
      "npm:showdown@1.3.0/dist/showdown",
      "route-highlight",
      "settings",
      "shared/au-code",
      "shared/collapse-panel",
      "shared/collapse-panel.html!github:systemjs/plugin-text@0.0.4",
      "shared/component-service",
      "shared/logger",
      "shared/logger.html!github:systemjs/plugin-text@0.0.4",
      "shared/markdown",
      "shared/registry",
      "shared/sample-runner",
      "shared/sample-runner.html!github:systemjs/plugin-text@0.0.4",
      "shared/sampleValueConverters",
      "shared/showcase.html!github:systemjs/plugin-text@0.0.4",
      "shared/theme-manager",
      "theme-selector/theme-selector",
      "theme-selector/theme-selector.html!github:systemjs/plugin-text@0.0.4"
    ]
  }
})