System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "optimisation.modules.system",
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  paths: {
    "*": "src/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  meta: {
    "showdown/dist/showdown": {
      "format": "global"
    }
  },
  map: {
    "aurelia-binding": "npm:aurelia-binding@1.1.0",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.1",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.2.0",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
    "aurelia-framework": "npm:aurelia-framework@1.0.8",
    "aurelia-http-client": "npm:aurelia-http-client@1.0.3",
    "aurelia-loader": "npm:aurelia-loader@1.0.0",
    "aurelia-logging": "npm:aurelia-logging@1.2.0",
    "aurelia-materialize-bridge": "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
    "aurelia-pal": "npm:aurelia-pal@1.1.1",
    "aurelia-polyfills": "npm:aurelia-polyfills@1.1.1",
    "aurelia-task-queue": "npm:aurelia-task-queue@1.1.0",
    "aurelia-templating": "npm:aurelia-templating@1.1.4",
    "aurelia-validation": "npm:aurelia-validation@1.0.0-beta.1.0.0",
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "clean-css": "npm:clean-css@3.4.22",
    "core-js": "npm:core-js@1.2.7",
    "css": "github:systemjs/plugin-css@0.1.20",
    "font-awesome": "npm:font-awesome@4.7.0",
    "google/code-prettify": "github:google/code-prettify@master",
    "jquery": "npm:jquery@2.2.4",
    "json": "github:systemjs/plugin-json@0.1.2",
    "materialize": "github:Dogfalo/materialize@0.97.8",
    "nprogress": "github:rstacruz/nprogress@0.2.0",
    "prettify": "npm:prettify@0.1.7",
    "prism": "github:PrismJS/prism@1.3.0",
    "showdown": "github:showdownjs/showdown@1.3.0",
    "showdown-prettify": "npm:showdown-prettify@1.3.0",
    "text": "github:systemjs/plugin-text@0.0.4",
    "github:Dogfalo/materialize@0.97.8": {
      "css": "github:systemjs/plugin-css@0.1.20",
      "jquery": "npm:jquery@2.2.4"
    },
    "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master": {
      "aurelia-binding": "npm:aurelia-binding@1.1.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
      "aurelia-pal": "npm:aurelia-pal@1.1.1",
      "aurelia-router": "npm:aurelia-router@1.1.0",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.1.0",
      "aurelia-templating": "npm:aurelia-templating@1.1.4",
      "jquery": "npm:jquery@2.2.4",
      "materialize": "github:Dogfalo/materialize@0.97.8"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.9"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-tty@0.1.0": {
      "tty-browserify": "npm:tty-browserify@0.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:rstacruz/nprogress@0.2.0": {
      "css": "github:systemjs/plugin-css@0.1.20"
    },
    "npm:amdefine@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-binding@1.1.0": {
      "aurelia-logging": "npm:aurelia-logging@1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
      "aurelia-pal": "npm:aurelia-pal@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.1.0"
    },
    "npm:aurelia-bootstrapper@1.0.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
      "aurelia-framework": "npm:aurelia-framework@1.0.8",
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.1.1",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.1.0",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.1.1",
      "aurelia-router": "npm:aurelia-router@1.1.0",
      "aurelia-templating": "npm:aurelia-templating@1.1.4",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.1.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.2.0",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.1"
    },
    "npm:aurelia-dependency-injection@1.2.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
      "aurelia-pal": "npm:aurelia-pal@1.1.1"
    },
    "npm:aurelia-event-aggregator@1.0.1": {
      "aurelia-logging": "npm:aurelia-logging@1.2.0"
    },
    "npm:aurelia-framework@1.0.8": {
      "aurelia-binding": "npm:aurelia-binding@1.1.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
      "aurelia-pal": "npm:aurelia-pal@1.1.1",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.1.0",
      "aurelia-templating": "npm:aurelia-templating@1.1.4"
    },
    "npm:aurelia-history-browser@1.0.0": {
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.1.1"
    },
    "npm:aurelia-http-client@1.0.3": {
      "aurelia-pal": "npm:aurelia-pal@1.1.1",
      "aurelia-path": "npm:aurelia-path@1.1.1"
    },
    "npm:aurelia-loader-default@1.0.0": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
      "aurelia-pal": "npm:aurelia-pal@1.1.1"
    },
    "npm:aurelia-loader@1.0.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
      "aurelia-path": "npm:aurelia-path@1.1.1"
    },
    "npm:aurelia-logging-console@1.0.0": {
      "aurelia-logging": "npm:aurelia-logging@1.2.0"
    },
    "npm:aurelia-metadata@1.0.2": {
      "aurelia-pal": "npm:aurelia-pal@1.1.1"
    },
    "npm:aurelia-pal-browser@1.1.0": {
      "aurelia-pal": "npm:aurelia-pal@1.1.1"
    },
    "npm:aurelia-polyfills@1.1.1": {
      "aurelia-pal": "npm:aurelia-pal@1.1.1"
    },
    "npm:aurelia-route-recognizer@1.1.0": {
      "aurelia-path": "npm:aurelia-path@1.1.1"
    },
    "npm:aurelia-router@1.1.0": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.2.0",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.2.0",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.1.0"
    },
    "npm:aurelia-task-queue@1.1.0": {
      "aurelia-pal": "npm:aurelia-pal@1.1.1"
    },
    "npm:aurelia-templating-binding@1.1.0": {
      "aurelia-binding": "npm:aurelia-binding@1.1.0",
      "aurelia-logging": "npm:aurelia-logging@1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.1.4"
    },
    "npm:aurelia-templating-resources@1.2.0": {
      "aurelia-binding": "npm:aurelia-binding@1.1.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
      "aurelia-pal": "npm:aurelia-pal@1.1.1",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.1.0",
      "aurelia-templating": "npm:aurelia-templating@1.1.4"
    },
    "npm:aurelia-templating-router@1.0.1": {
      "aurelia-binding": "npm:aurelia-binding@1.1.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
      "aurelia-pal": "npm:aurelia-pal@1.1.1",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-router": "npm:aurelia-router@1.1.0",
      "aurelia-templating": "npm:aurelia-templating@1.1.4"
    },
    "npm:aurelia-templating@1.1.4": {
      "aurelia-binding": "npm:aurelia-binding@1.1.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.2.0",
      "aurelia-loader": "npm:aurelia-loader@1.0.0",
      "aurelia-logging": "npm:aurelia-logging@1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.2",
      "aurelia-pal": "npm:aurelia-pal@1.1.1",
      "aurelia-path": "npm:aurelia-path@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.1.0"
    },
    "npm:aurelia-validation@1.0.0-beta.1.0.0": {
      "aurelia-binding": "npm:aurelia-binding@1.1.0",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.1.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.1.0",
      "aurelia-templating": "npm:aurelia-templating@1.1.4"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.8",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:clean-css@3.4.22": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "commander": "npm:commander@2.8.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.4.4",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:cliui@3.2.0": {
      "string-width": "npm:string-width@1.0.2",
      "strip-ansi": "npm:strip-ansi@3.0.1",
      "wrap-ansi": "npm:wrap-ansi@2.1.0"
    },
    "npm:commander@2.8.1": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graceful-readlink": "npm:graceful-readlink@1.0.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:config-chain@1.1.11": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "ini": "npm:ini@1.3.4",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "proto-list": "npm:proto-list@1.2.4",
      "url": "github:jspm/nodelibs-url@0.1.0"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:font-awesome@4.7.0": {
      "css": "github:systemjs/plugin-css@0.1.20"
    },
    "npm:graceful-readlink@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:ini@1.3.4": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:is-fullwidth-code-point@1.0.0": {
      "number-is-nan": "npm:number-is-nan@1.0.1"
    },
    "npm:js-prettify@1.4.0": {
      "config-chain": "npm:config-chain@1.1.11",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "mkdirp": "npm:mkdirp@0.3.5",
      "nopt": "npm:nopt@2.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:lcid@1.0.0": {
      "invert-kv": "npm:invert-kv@1.0.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:lodash@1.3.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:mkdirp@0.3.5": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:nopt@2.1.2": {
      "abbrev": "npm:abbrev@1.0.9",
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:os-locale@1.4.0": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "lcid": "npm:lcid@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:prettify@0.1.7": {
      "js-prettify": "npm:js-prettify@1.4.0",
      "lodash": "npm:lodash@1.3.1"
    },
    "npm:process@0.11.9": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:showdown-prettify@1.3.0": {
      "showdown": "npm:showdown@1.5.1"
    },
    "npm:showdown@1.5.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "yargs": "npm:yargs@3.32.0"
    },
    "npm:source-map@0.4.4": {
      "amdefine": "npm:amdefine@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string-width@1.0.2": {
      "code-point-at": "npm:code-point-at@1.1.0",
      "is-fullwidth-code-point": "npm:is-fullwidth-code-point@1.0.0",
      "strip-ansi": "npm:strip-ansi@3.0.1"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:strip-ansi@3.0.1": {
      "ansi-regex": "npm:ansi-regex@2.0.0"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:window-size@0.1.4": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tty": "github:jspm/nodelibs-tty@0.1.0"
    },
    "npm:wrap-ansi@2.1.0": {
      "string-width": "npm:string-width@1.0.2",
      "strip-ansi": "npm:strip-ansi@3.0.1"
    },
    "npm:y18n@3.2.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:yargs@3.32.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "camelcase": "npm:camelcase@2.1.1",
      "cliui": "npm:cliui@3.2.0",
      "decamelize": "npm:decamelize@1.2.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "os-locale": "npm:os-locale@1.4.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "string-width": "npm:string-width@1.0.2",
      "window-size": "npm:window-size@0.1.4",
      "y18n": "npm:y18n@3.2.1"
    }
  },
  bundles: {
    "materialize-1fc02f35a3.js": [
      "github:Dogfalo/materialize@0.97.8.js",
      "github:Dogfalo/materialize@0.97.8/css/materialize.css!github:systemjs/plugin-css@0.1.20.js",
      "github:Dogfalo/materialize@0.97.8/js/materialize.js",
      "npm:jquery@2.2.4.js",
      "npm:jquery@2.2.4/dist/jquery.js"
    ],
    "app-build-83a8c6eb9a.js": [
      "about/about.html!github:systemjs/plugin-text@0.0.4.js",
      "about/about.js",
      "app-colors.html!github:systemjs/plugin-text@0.0.4.js",
      "app.html!github:systemjs/plugin-text@0.0.4.js",
      "app.js",
      "color-switcher.html!github:systemjs/plugin-text@0.0.4.js",
      "github:PrismJS/prism@1.3.0.js",
      "github:PrismJS/prism@1.3.0/prism.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/autocomplete/autocomplete.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/badge/badge.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/box/box.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/breadcrumbs/breadcrumbs.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/breadcrumbs/breadcrumbs.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/breadcrumbs/breadcrumbs.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/breadcrumbs/instructionFilter.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/button/button.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/card/card.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/card/card.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/card/card.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/carousel/carousel-item.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/carousel/carousel-item.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/carousel/carousel.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/carousel/carousel.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/carousel/carousel.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/char-counter/char-counter.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/checkbox/checkbox.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/checkbox/checkbox.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/chip/chip.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/chip/chip.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/chip/chip.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/chip/chips.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/click-counter.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/click-counter.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collapsible/collapsible.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/collection-header.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/collection-header.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/collection-header.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/collection-item.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/collection-item.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/collection-item.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/collection.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/collection.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/md-collection-selector.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/md-collection-selector.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/collection/md-collection-selector.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/colors/colorValueConverters.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/colors/md-colors.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/colors/md-colors.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/common/attributeManager.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/common/attributes.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/common/constants.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/common/events.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/common/polyfills.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/config-builder.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/datepicker/datepicker-default-parser.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/datepicker/datepicker.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/dropdown/dropdown-element.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/dropdown/dropdown-element.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/dropdown/dropdown-fix.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/dropdown/dropdown.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/exports.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/fab/fab.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/fab/fab.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/file/file.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/file/file.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/footer/footer.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/index.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/input/input-prefix.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/input/input-update-service.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/input/input.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/input/input.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/input/input.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/modal/modal-trigger.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/modal/modal.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/navbar/navbar.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/navbar/navbar.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/navbar/navbar.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/pagination/pagination.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/pagination/pagination.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/parallax/parallax.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/progress/progress.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/progress/progress.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/pushpin/pushpin.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/radio/radio.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/radio/radio.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/range/range.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/range/range.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/range/range.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/scrollfire/scrollfire-patch.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/scrollfire/scrollfire-target.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/scrollfire/scrollfire.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/scrollspy/scrollspy.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/select/select.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/sidenav/sidenav-collapse.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/sidenav/sidenav.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/sidenav/sidenav.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/sidenav/sidenav.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/slider/slider.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/slider/slider.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/switch/switch.css!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/switch/switch.html!github:systemjs/plugin-text@0.0.4.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/switch/switch.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/tabs/tabs.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/toast/toastService.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/tooltip/tooltip.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/transitions/fadein-image.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/transitions/staggered-list.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/validation/validationRenderer.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/waves/waves.js",
      "github:aurelia-ui-toolkits/aurelia-materialize-bridge@master/well/md-well.html!github:systemjs/plugin-text@0.0.4.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "github:rstacruz/nprogress@0.2.0.js",
      "github:rstacruz/nprogress@0.2.0/nprogress.css!github:systemjs/plugin-css@0.1.20.js",
      "github:rstacruz/nprogress@0.2.0/nprogress.js",
      "github:showdownjs/showdown@1.3.0.js",
      "github:showdownjs/showdown@1.3.0/dist/showdown.js",
      "github:systemjs/plugin-css@0.1.20.js",
      "github:systemjs/plugin-css@0.1.20/css.js",
      "github:systemjs/plugin-json@0.1.2.js",
      "github:systemjs/plugin-json@0.1.2/json.js",
      "github:systemjs/plugin-text@0.0.4.js",
      "github:systemjs/plugin-text@0.0.4/text.js",
      "installation/installation.html!github:systemjs/plugin-text@0.0.4.js",
      "installation/installation.js",
      "loading-indicator.js",
      "main.js",
      "nav-bar.html!github:systemjs/plugin-text@0.0.4.js",
      "nav-bar.js",
      "npm:aurelia-binding@1.1.0.js",
      "npm:aurelia-binding@1.1.0/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.1.js",
      "npm:aurelia-bootstrapper@1.0.1/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.2.0.js",
      "npm:aurelia-dependency-injection@1.2.0/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.1.js",
      "npm:aurelia-event-aggregator@1.0.1/aurelia-event-aggregator.js",
      "npm:aurelia-framework@1.0.8.js",
      "npm:aurelia-framework@1.0.8/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0.js",
      "npm:aurelia-history-browser@1.0.0/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0.js",
      "npm:aurelia-history@1.0.0/aurelia-history.js",
      "npm:aurelia-http-client@1.0.3.js",
      "npm:aurelia-http-client@1.0.3/aurelia-http-client.js",
      "npm:aurelia-loader-default@1.0.0.js",
      "npm:aurelia-loader-default@1.0.0/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0.js",
      "npm:aurelia-loader@1.0.0/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0.js",
      "npm:aurelia-logging-console@1.0.0/aurelia-logging-console.js",
      "npm:aurelia-logging@1.2.0.js",
      "npm:aurelia-logging@1.2.0/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.2.js",
      "npm:aurelia-metadata@1.0.2/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.1.0.js",
      "npm:aurelia-pal-browser@1.1.0/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.1.1.js",
      "npm:aurelia-pal@1.1.1/aurelia-pal.js",
      "npm:aurelia-path@1.1.1.js",
      "npm:aurelia-path@1.1.1/aurelia-path.js",
      "npm:aurelia-polyfills@1.1.1.js",
      "npm:aurelia-polyfills@1.1.1/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.1.0.js",
      "npm:aurelia-route-recognizer@1.1.0/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.1.0.js",
      "npm:aurelia-router@1.1.0/aurelia-router.js",
      "npm:aurelia-task-queue@1.1.0.js",
      "npm:aurelia-task-queue@1.1.0/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.1.0.js",
      "npm:aurelia-templating-binding@1.1.0/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.2.0.js",
      "npm:aurelia-templating-resources@1.2.0/abstract-repeater.js",
      "npm:aurelia-templating-resources@1.2.0/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.2.0/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/attr-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/aurelia-hide-style.js",
      "npm:aurelia-templating-resources@1.2.0/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.2.0/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.2.0/binding-signaler.js",
      "npm:aurelia-templating-resources@1.2.0/compose.js",
      "npm:aurelia-templating-resources@1.2.0/css-resource.js",
      "npm:aurelia-templating-resources@1.2.0/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/dynamic-element.js",
      "npm:aurelia-templating-resources@1.2.0/focus.js",
      "npm:aurelia-templating-resources@1.2.0/hide.js",
      "npm:aurelia-templating-resources@1.2.0/html-resource-plugin.js",
      "npm:aurelia-templating-resources@1.2.0/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.2.0/if.js",
      "npm:aurelia-templating-resources@1.2.0/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.2.0/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.2.0/repeat.js",
      "npm:aurelia-templating-resources@1.2.0/replaceable.js",
      "npm:aurelia-templating-resources@1.2.0/sanitize-html.js",
      "npm:aurelia-templating-resources@1.2.0/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.2.0/show.js",
      "npm:aurelia-templating-resources@1.2.0/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.2.0/with.js",
      "npm:aurelia-templating-router@1.0.1.js",
      "npm:aurelia-templating-router@1.0.1/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.1/route-href.js",
      "npm:aurelia-templating-router@1.0.1/route-loader.js",
      "npm:aurelia-templating-router@1.0.1/router-view.js",
      "npm:aurelia-templating@1.1.4.js",
      "npm:aurelia-templating@1.1.4/aurelia-templating.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/aurelia-validation.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/implementation/rules.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/implementation/standard-validator.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/implementation/util.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/implementation/validation-messages.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/implementation/validation-parser.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/implementation/validation-rules.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/property-info.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/validate-binding-behavior-base.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/validate-binding-behavior.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/validate-result.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/validate-trigger.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/validation-controller-factory.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/validation-controller.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/validation-errors-custom-attribute.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/validation-renderer-custom-attribute.js",
      "npm:aurelia-validation@1.0.0-beta.1.0.0/validator.js",
      "npm:babel-core@5.8.38.js",
      "npm:babel-core@5.8.38/browser.js",
      "npm:core-js@1.2.7/library/core.js",
      "npm:core-js@1.2.7/library/core/_.js",
      "npm:core-js@1.2.7/library/core/delay.js",
      "npm:core-js@1.2.7/library/core/dict.js",
      "npm:core-js@1.2.7/library/core/function.js",
      "npm:core-js@1.2.7/library/core/index.js",
      "npm:core-js@1.2.7/library/core/log.js",
      "npm:core-js@1.2.7/library/core/number.js",
      "npm:core-js@1.2.7/library/core/object.js",
      "npm:core-js@1.2.7/library/core/string.js",
      "npm:core-js@1.2.7/library/es5.js",
      "npm:core-js@1.2.7/library/es5/index.js",
      "npm:core-js@1.2.7/library/es6.js",
      "npm:core-js@1.2.7/library/es6/array.js",
      "npm:core-js@1.2.7/library/es6/function.js",
      "npm:core-js@1.2.7/library/es6/index.js",
      "npm:core-js@1.2.7/library/es6/map.js",
      "npm:core-js@1.2.7/library/es6/math.js",
      "npm:core-js@1.2.7/library/es6/number.js",
      "npm:core-js@1.2.7/library/es6/object.js",
      "npm:core-js@1.2.7/library/es6/promise.js",
      "npm:core-js@1.2.7/library/es6/reflect.js",
      "npm:core-js@1.2.7/library/es6/regexp.js",
      "npm:core-js@1.2.7/library/es6/set.js",
      "npm:core-js@1.2.7/library/es6/string.js",
      "npm:core-js@1.2.7/library/es6/symbol.js",
      "npm:core-js@1.2.7/library/es6/weak-map.js",
      "npm:core-js@1.2.7/library/es6/weak-set.js",
      "npm:core-js@1.2.7/library/es7.js",
      "npm:core-js@1.2.7/library/es7/array.js",
      "npm:core-js@1.2.7/library/es7/index.js",
      "npm:core-js@1.2.7/library/es7/map.js",
      "npm:core-js@1.2.7/library/es7/object.js",
      "npm:core-js@1.2.7/library/es7/regexp.js",
      "npm:core-js@1.2.7/library/es7/set.js",
      "npm:core-js@1.2.7/library/es7/string.js",
      "npm:core-js@1.2.7/library/fn/_.js",
      "npm:core-js@1.2.7/library/fn/array.js",
      "npm:core-js@1.2.7/library/fn/array/concat.js",
      "npm:core-js@1.2.7/library/fn/array/copy-within.js",
      "npm:core-js@1.2.7/library/fn/array/entries.js",
      "npm:core-js@1.2.7/library/fn/array/every.js",
      "npm:core-js@1.2.7/library/fn/array/fill.js",
      "npm:core-js@1.2.7/library/fn/array/filter.js",
      "npm:core-js@1.2.7/library/fn/array/find-index.js",
      "npm:core-js@1.2.7/library/fn/array/find.js",
      "npm:core-js@1.2.7/library/fn/array/for-each.js",
      "npm:core-js@1.2.7/library/fn/array/from.js",
      "npm:core-js@1.2.7/library/fn/array/includes.js",
      "npm:core-js@1.2.7/library/fn/array/index-of.js",
      "npm:core-js@1.2.7/library/fn/array/index.js",
      "npm:core-js@1.2.7/library/fn/array/iterator.js",
      "npm:core-js@1.2.7/library/fn/array/join.js",
      "npm:core-js@1.2.7/library/fn/array/keys.js",
      "npm:core-js@1.2.7/library/fn/array/last-index-of.js",
      "npm:core-js@1.2.7/library/fn/array/map.js",
      "npm:core-js@1.2.7/library/fn/array/of.js",
      "npm:core-js@1.2.7/library/fn/array/pop.js",
      "npm:core-js@1.2.7/library/fn/array/push.js",
      "npm:core-js@1.2.7/library/fn/array/reduce-right.js",
      "npm:core-js@1.2.7/library/fn/array/reduce.js",
      "npm:core-js@1.2.7/library/fn/array/reverse.js",
      "npm:core-js@1.2.7/library/fn/array/shift.js",
      "npm:core-js@1.2.7/library/fn/array/slice.js",
      "npm:core-js@1.2.7/library/fn/array/some.js",
      "npm:core-js@1.2.7/library/fn/array/sort.js",
      "npm:core-js@1.2.7/library/fn/array/splice.js",
      "npm:core-js@1.2.7/library/fn/array/unshift.js",
      "npm:core-js@1.2.7/library/fn/array/values.js",
      "npm:core-js@1.2.7/library/fn/clear-immediate.js",
      "npm:core-js@1.2.7/library/fn/delay.js",
      "npm:core-js@1.2.7/library/fn/dict.js",
      "npm:core-js@1.2.7/library/fn/function.js",
      "npm:core-js@1.2.7/library/fn/function/has-instance.js",
      "npm:core-js@1.2.7/library/fn/function/index.js",
      "npm:core-js@1.2.7/library/fn/function/name.js",
      "npm:core-js@1.2.7/library/fn/function/part.js",
      "npm:core-js@1.2.7/library/fn/get-iterator-method.js",
      "npm:core-js@1.2.7/library/fn/get-iterator.js",
      "npm:core-js@1.2.7/library/fn/html-collection.js",
      "npm:core-js@1.2.7/library/fn/html-collection/index.js",
      "npm:core-js@1.2.7/library/fn/html-collection/iterator.js",
      "npm:core-js@1.2.7/library/fn/is-iterable.js",
      "npm:core-js@1.2.7/library/fn/json/stringify.js",
      "npm:core-js@1.2.7/library/fn/log.js",
      "npm:core-js@1.2.7/library/fn/map.js",
      "npm:core-js@1.2.7/library/fn/math.js",
      "npm:core-js@1.2.7/library/fn/math/acosh.js",
      "npm:core-js@1.2.7/library/fn/math/asinh.js",
      "npm:core-js@1.2.7/library/fn/math/atanh.js",
      "npm:core-js@1.2.7/library/fn/math/cbrt.js",
      "npm:core-js@1.2.7/library/fn/math/clz32.js",
      "npm:core-js@1.2.7/library/fn/math/cosh.js",
      "npm:core-js@1.2.7/library/fn/math/expm1.js",
      "npm:core-js@1.2.7/library/fn/math/fround.js",
      "npm:core-js@1.2.7/library/fn/math/hypot.js",
      "npm:core-js@1.2.7/library/fn/math/imul.js",
      "npm:core-js@1.2.7/library/fn/math/index.js",
      "npm:core-js@1.2.7/library/fn/math/log10.js",
      "npm:core-js@1.2.7/library/fn/math/log1p.js",
      "npm:core-js@1.2.7/library/fn/math/log2.js",
      "npm:core-js@1.2.7/library/fn/math/sign.js",
      "npm:core-js@1.2.7/library/fn/math/sinh.js",
      "npm:core-js@1.2.7/library/fn/math/tanh.js",
      "npm:core-js@1.2.7/library/fn/math/trunc.js",
      "npm:core-js@1.2.7/library/fn/node-list.js",
      "npm:core-js@1.2.7/library/fn/node-list/index.js",
      "npm:core-js@1.2.7/library/fn/node-list/iterator.js",
      "npm:core-js@1.2.7/library/fn/number.js",
      "npm:core-js@1.2.7/library/fn/number/epsilon.js",
      "npm:core-js@1.2.7/library/fn/number/index.js",
      "npm:core-js@1.2.7/library/fn/number/is-finite.js",
      "npm:core-js@1.2.7/library/fn/number/is-integer.js",
      "npm:core-js@1.2.7/library/fn/number/is-nan.js",
      "npm:core-js@1.2.7/library/fn/number/is-safe-integer.js",
      "npm:core-js@1.2.7/library/fn/number/iterator.js",
      "npm:core-js@1.2.7/library/fn/number/max-safe-integer.js",
      "npm:core-js@1.2.7/library/fn/number/min-safe-integer.js",
      "npm:core-js@1.2.7/library/fn/number/parse-float.js",
      "npm:core-js@1.2.7/library/fn/number/parse-int.js",
      "npm:core-js@1.2.7/library/fn/object.js",
      "npm:core-js@1.2.7/library/fn/object/assign.js",
      "npm:core-js@1.2.7/library/fn/object/classof.js",
      "npm:core-js@1.2.7/library/fn/object/create.js",
      "npm:core-js@1.2.7/library/fn/object/define-properties.js",
      "npm:core-js@1.2.7/library/fn/object/define-property.js",
      "npm:core-js@1.2.7/library/fn/object/define.js",
      "npm:core-js@1.2.7/library/fn/object/entries.js",
      "npm:core-js@1.2.7/library/fn/object/freeze.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-descriptors.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-names.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-symbols.js",
      "npm:core-js@1.2.7/library/fn/object/get-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/object/index.js",
      "npm:core-js@1.2.7/library/fn/object/is-extensible.js",
      "npm:core-js@1.2.7/library/fn/object/is-frozen.js",
      "npm:core-js@1.2.7/library/fn/object/is-object.js",
      "npm:core-js@1.2.7/library/fn/object/is-sealed.js",
      "npm:core-js@1.2.7/library/fn/object/is.js",
      "npm:core-js@1.2.7/library/fn/object/keys.js",
      "npm:core-js@1.2.7/library/fn/object/make.js",
      "npm:core-js@1.2.7/library/fn/object/prevent-extensions.js",
      "npm:core-js@1.2.7/library/fn/object/seal.js",
      "npm:core-js@1.2.7/library/fn/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/object/values.js",
      "npm:core-js@1.2.7/library/fn/promise.js",
      "npm:core-js@1.2.7/library/fn/reflect.js",
      "npm:core-js@1.2.7/library/fn/reflect/apply.js",
      "npm:core-js@1.2.7/library/fn/reflect/construct.js",
      "npm:core-js@1.2.7/library/fn/reflect/define-property.js",
      "npm:core-js@1.2.7/library/fn/reflect/delete-property.js",
      "npm:core-js@1.2.7/library/fn/reflect/enumerate.js",
      "npm:core-js@1.2.7/library/fn/reflect/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/fn/reflect/get-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/reflect/get.js",
      "npm:core-js@1.2.7/library/fn/reflect/has.js",
      "npm:core-js@1.2.7/library/fn/reflect/index.js",
      "npm:core-js@1.2.7/library/fn/reflect/is-extensible.js",
      "npm:core-js@1.2.7/library/fn/reflect/own-keys.js",
      "npm:core-js@1.2.7/library/fn/reflect/prevent-extensions.js",
      "npm:core-js@1.2.7/library/fn/reflect/set-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/reflect/set.js",
      "npm:core-js@1.2.7/library/fn/regexp.js",
      "npm:core-js@1.2.7/library/fn/regexp/escape.js",
      "npm:core-js@1.2.7/library/fn/regexp/index.js",
      "npm:core-js@1.2.7/library/fn/set-immediate.js",
      "npm:core-js@1.2.7/library/fn/set-interval.js",
      "npm:core-js@1.2.7/library/fn/set-timeout.js",
      "npm:core-js@1.2.7/library/fn/set.js",
      "npm:core-js@1.2.7/library/fn/string.js",
      "npm:core-js@1.2.7/library/fn/string/at.js",
      "npm:core-js@1.2.7/library/fn/string/code-point-at.js",
      "npm:core-js@1.2.7/library/fn/string/ends-with.js",
      "npm:core-js@1.2.7/library/fn/string/escape-html.js",
      "npm:core-js@1.2.7/library/fn/string/from-code-point.js",
      "npm:core-js@1.2.7/library/fn/string/includes.js",
      "npm:core-js@1.2.7/library/fn/string/index.js",
      "npm:core-js@1.2.7/library/fn/string/iterator.js",
      "npm:core-js@1.2.7/library/fn/string/pad-left.js",
      "npm:core-js@1.2.7/library/fn/string/pad-right.js",
      "npm:core-js@1.2.7/library/fn/string/raw.js",
      "npm:core-js@1.2.7/library/fn/string/repeat.js",
      "npm:core-js@1.2.7/library/fn/string/starts-with.js",
      "npm:core-js@1.2.7/library/fn/string/trim-left.js",
      "npm:core-js@1.2.7/library/fn/string/trim-right.js",
      "npm:core-js@1.2.7/library/fn/string/trim.js",
      "npm:core-js@1.2.7/library/fn/string/unescape-html.js",
      "npm:core-js@1.2.7/library/fn/symbol.js",
      "npm:core-js@1.2.7/library/fn/symbol/for.js",
      "npm:core-js@1.2.7/library/fn/symbol/has-instance.js",
      "npm:core-js@1.2.7/library/fn/symbol/index.js",
      "npm:core-js@1.2.7/library/fn/symbol/is-concat-spreadable.js",
      "npm:core-js@1.2.7/library/fn/symbol/iterator.js",
      "npm:core-js@1.2.7/library/fn/symbol/key-for.js",
      "npm:core-js@1.2.7/library/fn/symbol/match.js",
      "npm:core-js@1.2.7/library/fn/symbol/replace.js",
      "npm:core-js@1.2.7/library/fn/symbol/search.js",
      "npm:core-js@1.2.7/library/fn/symbol/species.js",
      "npm:core-js@1.2.7/library/fn/symbol/split.js",
      "npm:core-js@1.2.7/library/fn/symbol/to-primitive.js",
      "npm:core-js@1.2.7/library/fn/symbol/to-string-tag.js",
      "npm:core-js@1.2.7/library/fn/symbol/unscopables.js",
      "npm:core-js@1.2.7/library/fn/weak-map.js",
      "npm:core-js@1.2.7/library/fn/weak-set.js",
      "npm:core-js@1.2.7/library/index.js",
      "npm:core-js@1.2.7/library/js.js",
      "npm:core-js@1.2.7/library/js/array.js",
      "npm:core-js@1.2.7/library/js/index.js",
      "npm:core-js@1.2.7/library/modules/$.a-function.js",
      "npm:core-js@1.2.7/library/modules/$.add-to-unscopables.js",
      "npm:core-js@1.2.7/library/modules/$.an-object.js",
      "npm:core-js@1.2.7/library/modules/$.array-copy-within.js",
      "npm:core-js@1.2.7/library/modules/$.array-fill.js",
      "npm:core-js@1.2.7/library/modules/$.array-includes.js",
      "npm:core-js@1.2.7/library/modules/$.array-methods.js",
      "npm:core-js@1.2.7/library/modules/$.array-species-create.js",
      "npm:core-js@1.2.7/library/modules/$.buffer.js",
      "npm:core-js@1.2.7/library/modules/$.classof.js",
      "npm:core-js@1.2.7/library/modules/$.cof.js",
      "npm:core-js@1.2.7/library/modules/$.collection-strong.js",
      "npm:core-js@1.2.7/library/modules/$.collection-to-json.js",
      "npm:core-js@1.2.7/library/modules/$.collection-weak.js",
      "npm:core-js@1.2.7/library/modules/$.collection.js",
      "npm:core-js@1.2.7/library/modules/$.core.js",
      "npm:core-js@1.2.7/library/modules/$.ctx.js",
      "npm:core-js@1.2.7/library/modules/$.defined.js",
      "npm:core-js@1.2.7/library/modules/$.descriptors.js",
      "npm:core-js@1.2.7/library/modules/$.dom-create.js",
      "npm:core-js@1.2.7/library/modules/$.enum-keys.js",
      "npm:core-js@1.2.7/library/modules/$.export.js",
      "npm:core-js@1.2.7/library/modules/$.fails-is-regexp.js",
      "npm:core-js@1.2.7/library/modules/$.fails.js",
      "npm:core-js@1.2.7/library/modules/$.fix-re-wks.js",
      "npm:core-js@1.2.7/library/modules/$.flags.js",
      "npm:core-js@1.2.7/library/modules/$.for-of.js",
      "npm:core-js@1.2.7/library/modules/$.get-names.js",
      "npm:core-js@1.2.7/library/modules/$.global.js",
      "npm:core-js@1.2.7/library/modules/$.has.js",
      "npm:core-js@1.2.7/library/modules/$.hide.js",
      "npm:core-js@1.2.7/library/modules/$.html.js",
      "npm:core-js@1.2.7/library/modules/$.invoke.js",
      "npm:core-js@1.2.7/library/modules/$.iobject.js",
      "npm:core-js@1.2.7/library/modules/$.is-array-iter.js",
      "npm:core-js@1.2.7/library/modules/$.is-array.js",
      "npm:core-js@1.2.7/library/modules/$.is-integer.js",
      "npm:core-js@1.2.7/library/modules/$.is-object.js",
      "npm:core-js@1.2.7/library/modules/$.is-regexp.js",
      "npm:core-js@1.2.7/library/modules/$.iter-call.js",
      "npm:core-js@1.2.7/library/modules/$.iter-create.js",
      "npm:core-js@1.2.7/library/modules/$.iter-define.js",
      "npm:core-js@1.2.7/library/modules/$.iter-detect.js",
      "npm:core-js@1.2.7/library/modules/$.iter-step.js",
      "npm:core-js@1.2.7/library/modules/$.iterators.js",
      "npm:core-js@1.2.7/library/modules/$.js",
      "npm:core-js@1.2.7/library/modules/$.keyof.js",
      "npm:core-js@1.2.7/library/modules/$.library.js",
      "npm:core-js@1.2.7/library/modules/$.math-expm1.js",
      "npm:core-js@1.2.7/library/modules/$.math-log1p.js",
      "npm:core-js@1.2.7/library/modules/$.math-sign.js",
      "npm:core-js@1.2.7/library/modules/$.microtask.js",
      "npm:core-js@1.2.7/library/modules/$.object-assign.js",
      "npm:core-js@1.2.7/library/modules/$.object-define.js",
      "npm:core-js@1.2.7/library/modules/$.object-sap.js",
      "npm:core-js@1.2.7/library/modules/$.object-to-array.js",
      "npm:core-js@1.2.7/library/modules/$.own-keys.js",
      "npm:core-js@1.2.7/library/modules/$.partial.js",
      "npm:core-js@1.2.7/library/modules/$.path.js",
      "npm:core-js@1.2.7/library/modules/$.property-desc.js",
      "npm:core-js@1.2.7/library/modules/$.redefine-all.js",
      "npm:core-js@1.2.7/library/modules/$.redefine.js",
      "npm:core-js@1.2.7/library/modules/$.replacer.js",
      "npm:core-js@1.2.7/library/modules/$.same-value.js",
      "npm:core-js@1.2.7/library/modules/$.set-proto.js",
      "npm:core-js@1.2.7/library/modules/$.set-species.js",
      "npm:core-js@1.2.7/library/modules/$.set-to-string-tag.js",
      "npm:core-js@1.2.7/library/modules/$.shared.js",
      "npm:core-js@1.2.7/library/modules/$.species-constructor.js",
      "npm:core-js@1.2.7/library/modules/$.strict-new.js",
      "npm:core-js@1.2.7/library/modules/$.string-at.js",
      "npm:core-js@1.2.7/library/modules/$.string-context.js",
      "npm:core-js@1.2.7/library/modules/$.string-pad.js",
      "npm:core-js@1.2.7/library/modules/$.string-repeat.js",
      "npm:core-js@1.2.7/library/modules/$.string-trim.js",
      "npm:core-js@1.2.7/library/modules/$.task.js",
      "npm:core-js@1.2.7/library/modules/$.to-index.js",
      "npm:core-js@1.2.7/library/modules/$.to-integer.js",
      "npm:core-js@1.2.7/library/modules/$.to-iobject.js",
      "npm:core-js@1.2.7/library/modules/$.to-length.js",
      "npm:core-js@1.2.7/library/modules/$.to-object.js",
      "npm:core-js@1.2.7/library/modules/$.to-primitive.js",
      "npm:core-js@1.2.7/library/modules/$.typed-array.js",
      "npm:core-js@1.2.7/library/modules/$.typed.js",
      "npm:core-js@1.2.7/library/modules/$.uid.js",
      "npm:core-js@1.2.7/library/modules/$.wks.js",
      "npm:core-js@1.2.7/library/modules/core.delay.js",
      "npm:core-js@1.2.7/library/modules/core.dict.js",
      "npm:core-js@1.2.7/library/modules/core.function.part.js",
      "npm:core-js@1.2.7/library/modules/core.get-iterator-method.js",
      "npm:core-js@1.2.7/library/modules/core.get-iterator.js",
      "npm:core-js@1.2.7/library/modules/core.is-iterable.js",
      "npm:core-js@1.2.7/library/modules/core.log.js",
      "npm:core-js@1.2.7/library/modules/core.number.iterator.js",
      "npm:core-js@1.2.7/library/modules/core.object.classof.js",
      "npm:core-js@1.2.7/library/modules/core.object.define.js",
      "npm:core-js@1.2.7/library/modules/core.object.is-object.js",
      "npm:core-js@1.2.7/library/modules/core.object.make.js",
      "npm:core-js@1.2.7/library/modules/core.string.escape-html.js",
      "npm:core-js@1.2.7/library/modules/core.string.unescape-html.js",
      "npm:core-js@1.2.7/library/modules/es5.js",
      "npm:core-js@1.2.7/library/modules/es6.array.copy-within.js",
      "npm:core-js@1.2.7/library/modules/es6.array.fill.js",
      "npm:core-js@1.2.7/library/modules/es6.array.find-index.js",
      "npm:core-js@1.2.7/library/modules/es6.array.find.js",
      "npm:core-js@1.2.7/library/modules/es6.array.from.js",
      "npm:core-js@1.2.7/library/modules/es6.array.iterator.js",
      "npm:core-js@1.2.7/library/modules/es6.array.of.js",
      "npm:core-js@1.2.7/library/modules/es6.array.species.js",
      "npm:core-js@1.2.7/library/modules/es6.date.to-string.js",
      "npm:core-js@1.2.7/library/modules/es6.function.has-instance.js",
      "npm:core-js@1.2.7/library/modules/es6.function.name.js",
      "npm:core-js@1.2.7/library/modules/es6.map.js",
      "npm:core-js@1.2.7/library/modules/es6.math.acosh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.asinh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.atanh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.cbrt.js",
      "npm:core-js@1.2.7/library/modules/es6.math.clz32.js",
      "npm:core-js@1.2.7/library/modules/es6.math.cosh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.expm1.js",
      "npm:core-js@1.2.7/library/modules/es6.math.fround.js",
      "npm:core-js@1.2.7/library/modules/es6.math.hypot.js",
      "npm:core-js@1.2.7/library/modules/es6.math.imul.js",
      "npm:core-js@1.2.7/library/modules/es6.math.log10.js",
      "npm:core-js@1.2.7/library/modules/es6.math.log1p.js",
      "npm:core-js@1.2.7/library/modules/es6.math.log2.js",
      "npm:core-js@1.2.7/library/modules/es6.math.sign.js",
      "npm:core-js@1.2.7/library/modules/es6.math.sinh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.tanh.js",
      "npm:core-js@1.2.7/library/modules/es6.math.trunc.js",
      "npm:core-js@1.2.7/library/modules/es6.number.constructor.js",
      "npm:core-js@1.2.7/library/modules/es6.number.epsilon.js",
      "npm:core-js@1.2.7/library/modules/es6.number.is-finite.js",
      "npm:core-js@1.2.7/library/modules/es6.number.is-integer.js",
      "npm:core-js@1.2.7/library/modules/es6.number.is-nan.js",
      "npm:core-js@1.2.7/library/modules/es6.number.is-safe-integer.js",
      "npm:core-js@1.2.7/library/modules/es6.number.max-safe-integer.js",
      "npm:core-js@1.2.7/library/modules/es6.number.min-safe-integer.js",
      "npm:core-js@1.2.7/library/modules/es6.number.parse-float.js",
      "npm:core-js@1.2.7/library/modules/es6.number.parse-int.js",
      "npm:core-js@1.2.7/library/modules/es6.object.assign.js",
      "npm:core-js@1.2.7/library/modules/es6.object.freeze.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-own-property-names.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/es6.object.is-extensible.js",
      "npm:core-js@1.2.7/library/modules/es6.object.is-frozen.js",
      "npm:core-js@1.2.7/library/modules/es6.object.is-sealed.js",
      "npm:core-js@1.2.7/library/modules/es6.object.is.js",
      "npm:core-js@1.2.7/library/modules/es6.object.keys.js",
      "npm:core-js@1.2.7/library/modules/es6.object.prevent-extensions.js",
      "npm:core-js@1.2.7/library/modules/es6.object.seal.js",
      "npm:core-js@1.2.7/library/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/es6.object.to-string.js",
      "npm:core-js@1.2.7/library/modules/es6.promise.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.apply.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.construct.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.define-property.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.delete-property.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.enumerate.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.get-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.get.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.has.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.is-extensible.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.own-keys.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.prevent-extensions.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/es6.reflect.set.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.constructor.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.flags.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.match.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.replace.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.search.js",
      "npm:core-js@1.2.7/library/modules/es6.regexp.split.js",
      "npm:core-js@1.2.7/library/modules/es6.set.js",
      "npm:core-js@1.2.7/library/modules/es6.string.code-point-at.js",
      "npm:core-js@1.2.7/library/modules/es6.string.ends-with.js",
      "npm:core-js@1.2.7/library/modules/es6.string.from-code-point.js",
      "npm:core-js@1.2.7/library/modules/es6.string.includes.js",
      "npm:core-js@1.2.7/library/modules/es6.string.iterator.js",
      "npm:core-js@1.2.7/library/modules/es6.string.raw.js",
      "npm:core-js@1.2.7/library/modules/es6.string.repeat.js",
      "npm:core-js@1.2.7/library/modules/es6.string.starts-with.js",
      "npm:core-js@1.2.7/library/modules/es6.string.trim.js",
      "npm:core-js@1.2.7/library/modules/es6.symbol.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.array-buffer.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.data-view.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.float32-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.float64-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.int16-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.int32-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.int8-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.uint16-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.uint32-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.uint8-array.js",
      "npm:core-js@1.2.7/library/modules/es6.typed.uint8-clamped-array.js",
      "npm:core-js@1.2.7/library/modules/es6.weak-map.js",
      "npm:core-js@1.2.7/library/modules/es6.weak-set.js",
      "npm:core-js@1.2.7/library/modules/es7.array.includes.js",
      "npm:core-js@1.2.7/library/modules/es7.map.to-json.js",
      "npm:core-js@1.2.7/library/modules/es7.object.entries.js",
      "npm:core-js@1.2.7/library/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@1.2.7/library/modules/es7.object.values.js",
      "npm:core-js@1.2.7/library/modules/es7.regexp.escape.js",
      "npm:core-js@1.2.7/library/modules/es7.set.to-json.js",
      "npm:core-js@1.2.7/library/modules/es7.string.at.js",
      "npm:core-js@1.2.7/library/modules/es7.string.pad-left.js",
      "npm:core-js@1.2.7/library/modules/es7.string.pad-right.js",
      "npm:core-js@1.2.7/library/modules/es7.string.trim-left.js",
      "npm:core-js@1.2.7/library/modules/es7.string.trim-right.js",
      "npm:core-js@1.2.7/library/modules/js.array.statics.js",
      "npm:core-js@1.2.7/library/modules/web.dom.iterable.js",
      "npm:core-js@1.2.7/library/modules/web.immediate.js",
      "npm:core-js@1.2.7/library/modules/web.timers.js",
      "npm:core-js@1.2.7/library/shim.js",
      "npm:core-js@1.2.7/library/web.js",
      "npm:core-js@1.2.7/library/web/dom.js",
      "npm:core-js@1.2.7/library/web/immediate.js",
      "npm:core-js@1.2.7/library/web/index.js",
      "npm:core-js@1.2.7/library/web/timers.js",
      "npm:jquery@2.2.4.js",
      "npm:jquery@2.2.4/dist/jquery.js",
      "npm:process@0.11.9.js",
      "npm:process@0.11.9/browser.js",
      "npm:showdown-prettify@1.3.0.js",
      "npm:showdown-prettify@1.3.0/dist/showdown-prettify.js",
      "npm:showdown@1.5.1.js",
      "npm:showdown@1.5.1/dist/showdown.js",
      "route-highlight.js",
      "settings.js",
      "shared/au-code.js",
      "shared/collapse-panel.html!github:systemjs/plugin-text@0.0.4.js",
      "shared/collapse-panel.js",
      "shared/component-service.js",
      "shared/logger.html!github:systemjs/plugin-text@0.0.4.js",
      "shared/logger.js",
      "shared/markdown.js",
      "shared/registry.js",
      "shared/sample-runner.html!github:systemjs/plugin-text@0.0.4.js",
      "shared/sample-runner.js",
      "shared/sampleValueConverters.js",
      "shared/showcase.html!github:systemjs/plugin-text@0.0.4.js",
      "shared/theme-manager.js",
      "theme-selector/theme-selector.html!github:systemjs/plugin-text@0.0.4.js",
      "theme-selector/theme-selector.js"
    ]
  }
});